import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import ReactDOM from 'react-dom';
import { useTranslation } from 'react-i18next';
import { Search, X, Loader2, Check } from 'lucide-react';
import { toast } from '../../lib/toast';
import {
    lookupMetadata,
    recognizePdf,
    translateUrl,
} from '../../shared/api/resource-lookup';
import { LABEL_TO_ZOTERO_TYPE, ZOTERO_TYPE_LABELS, ZOTERO_TO_CSL_TYPE } from './zoteroSchema';
import { uiLangToZoteroLocale } from './zoteroLocale';
import { isFieldRelevantForType } from './recursosZoteroMapping';
import { validateIdentifier } from './identifierValidators';
import { useModalKeyboard } from '../../hooks/useModalKeyboard';

/**
 * Normalizes an "Item Type" value from the lookup (it may come as the canonical
 * Zotero key `journalArticle` or as the translated label `Article de revista
 * acadèmica`) into the canonical key. Returns null if it's not recognized.
 */
function resolveZoteroType(raw) {
    if (!raw || typeof raw !== 'string') return null;
    if (raw in ZOTERO_TO_CSL_TYPE) return raw;          // already canonical
    for (const loc of Object.keys(LABEL_TO_ZOTERO_TYPE)) {
        const zot = LABEL_TO_ZOTERO_TYPE[loc][raw];
        if (zot) return zot;
    }
    return null;
}

/**
 * Metadata enrichment modal based on DOI / ISBN / arXiv / PMID / URL.
 *
 * Flow:
 *   1. The user clicks "Fill metadata" in the Properties panel of a
 *      Resources page (button rendered in the `BlockEditor`).
 *   2. The modal opens, detecting identifiers in the current fields
 *      (DOI > arXiv > ISBN > URL — same priority as the backend).
 *      The user can change the value or force a specific identifier.
 *   3. Clicks "Search" → POST to `/api/vault/lookup-metadata`.
 *   4. Shows a table with each detected field:
 *        - checkbox (default: checked only if the current one is empty)
 *        - field name
 *        - current value (gray)
 *        - proposed value (black)
 *   5. "Apply selection" → callback with the patch of selected fields.
 *      It calls `onApply({fieldName: newValue, ...})` because the caller
 *      already has handleMetaChange or the backend PATCH.
 *
 * Never writes anything on its own; always requires user confirmation.
 */
const SOURCE_LABELS = {
    crossref: 'CrossRef (DOI)',
    openlibrary: 'Open Library (ISBN)',
    arxiv: 'arXiv (preprint)',
    pubmed: 'PubMed (PMID)',
    web: 'Zotero translation-server (web)',
    url: 'Open Graph / meta tags (URL)',
    pdf: 'PDF',
};

/** Returns the translated Zotero item-type label for the active UI language.
 *  Falls back to the canonical key (`zoteroType`) if the locale has no label. */
function zoteroTypeLabel(zoteroType, uiLanguage) {
    if (!zoteroType) return null;
    const locale = uiLangToZoteroLocale(uiLanguage);
    return ZOTERO_TYPE_LABELS[locale]?.[zoteroType] || zoteroType;
}

export const MetadataLookupModal = ({
    isOpen,
    onClose,
    onApply,
    onCreate,
    mode = 'enrich',
    currentMetadata = {},
}) => {
    const { t, i18n } = useTranslation();
    // State: editable identifiers + selection + response
    const [doi, setDoi] = useState('');
    const [isbn, setIsbn] = useState('');
    const [arxivId, setArxivId] = useState('');
    const [pmid, setPmid] = useState('');
    const [url, setUrl] = useState('');
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState(null); // { source, identifier, suggested, error }
    const [selectedFields, setSelectedFields] = useState({}); // { fieldName: bool }
    const firstInputRef = useRef(null);
    const pdfInputRef = useRef(null);
    const panelRef = useRef(null);
    // Latest currentMetadata read through a ref so the seed effect below can
    // depend only on `isOpen`. Callers frequently pass an inline object (or omit
    // it, defaulting to a fresh `{}` every render); depending on its identity
    // would re-run the seed effect on every keystroke, wiping the inputs and
    // stealing focus back to the first field.
    const currentMetadataRef = useRef(currentMetadata);
    useEffect(() => {
        currentMetadataRef.current = currentMetadata;
    });

    // Common post-processing of a response (lookup by identifier or by PDF):
    // saves the result and pre-checks the fields that are currently empty.
    const populateFromResult = useCallback((data) => {
        const sug = data?.suggested || {};
        // 'create' mode (creation from the table's New menu): with no
        // confirmation step — once there's data, it creates the record directly and closes.
        // The `suggested` already carries the `Citation Key` generated by the backend.
        if (mode === 'create') {
            if (data?.error || Object.keys(sug).length === 0) {
                toast.error(data?.error || t('metadata_lookup.no_data', {
                    defaultValue: "No data found.",
                }));
                return;
            }
            onCreate?.(sug);
            onClose?.();
            return;
        }
        setResult(data);
        const newSel = {};
        Object.keys(sug).forEach((k) => {
            const current = currentMetadata?.[k];
            const isEmpty = current === null || current === undefined || current === '' || (Array.isArray(current) && current.length === 0);
            newSel[k] = isEmpty;
        });
        setSelectedFields(newSel);
        if (data?.error) toast.error(data.error);
    }, [currentMetadata, mode, onCreate, onClose, t]);

    // Detect current identifiers on open. Depends ONLY on `isOpen` so it seeds
    // the fields on the open transition and never re-runs while the user types
    // (see currentMetadataRef above for why the identity dependency is unsafe).
    useEffect(() => {
        if (!isOpen) return;
        const cm = currentMetadataRef.current || {};
        setDoi(String(cm.DOI || '').trim());
        setIsbn(String(cm.ISBN || '').trim());
        setArxivId('');
        setPmid(String(cm.PMID || '').trim());
        setUrl(String(cm.URL || '').trim());
        setResult(null);
        setSelectedFields({});
        const id = requestAnimationFrame(() => {
            try { firstInputRef.current?.focus(); } catch { /* ignore */ }
        });
        return () => cancelAnimationFrame(id);
    }, [isOpen]);

    const handleSearch = useCallback(async () => {
        const payload = {
            doi: doi.trim() || undefined,
            isbn: isbn.trim() || undefined,
            arxiv: arxivId.trim() || undefined,
            pmid: pmid.trim() || undefined,
            url: url.trim() || undefined,
        };
        if (!payload.doi && !payload.isbn && !payload.arxiv && !payload.pmid && !payload.url) {
            toast.error(t('metadata_lookup.no_identifier', {
                defaultValue: "A DOI, ISBN, arXiv id, PMID or URL is required",
            }));
            return;
        }
        setLoading(true);
        try {
            const onlyUrl = payload.url && !payload.doi && !payload.isbn && !payload.arxiv && !payload.pmid;
            let data;
            if (onlyUrl) {
                // Rich web capture via Zotero translation-server; if it doesn't respond,
                // fallback to the meta tags (Open Graph/Highwire) from /lookup-metadata.
                data = await translateUrl({ url: payload.url });
                const sug = data?.suggested;
                if (data?.error && (!sug || Object.keys(sug).length === 0)) {
                    data = await lookupMetadata(payload);
                }
            } else {
                data = await lookupMetadata(payload);
            }
            populateFromResult(data);
        } catch (err) {
            console.error('lookup failed:', err?.message);
            toast.error(t('metadata_lookup.fetch_failed', {
                defaultValue: "Error querying external sources",
            }));
        } finally {
            setLoading(false);
        }
    }, [doi, isbn, arxivId, pmid, url, populateFromResult, t]);

    // P4: recognition from a PDF (extracts DOI/arXiv → lookup).
    const handlePdfUpload = useCallback(async (e) => {
        const file = e.target.files?.[0];
        e.target.value = ''; // allows reselecting the same file
        if (!file) return;
        setLoading(true);
        try {
            const data = await recognizePdf(file);
            populateFromResult(data);
        } catch (err) {
            console.error('pdf recognize failed:', err?.message);
            toast.error(t('metadata_lookup.pdf_failed', {
                defaultValue: "Error recognizing the PDF",
            }));
        } finally {
            setLoading(false);
        }
    }, [populateFromResult, t]);

    const handleApply = useCallback(() => {
        const sug = result?.suggested || {};
        const patch = {};
        for (const [k, v] of Object.entries(sug)) {
            if (selectedFields[k]) patch[k] = v;
        }
        if (Object.keys(patch).length === 0) {
            toast.error(t('metadata_lookup.nothing_selected', {
                defaultValue: "No field selected",
            }));
            return;
        }
        try {
            onApply?.(patch);
            toast.success(t('metadata_lookup.applied', {
                defaultValue: `${Object.keys(patch).length} camps actualitzats`,
                count: Object.keys(patch).length,
            }));
            onClose?.();
        } catch (err) {
            console.error('apply failed:', err?.message);
            toast.error(t('metadata_lookup.apply_failed', {
                defaultValue: "Error applying the changes",
            }));
        }
    }, [result, selectedFields, onApply, onClose, t]);

    const handleKeyDown = useCallback((e) => {
        // Esc is handled by useModalKeyboard (capture, robust). Here we only
        // we keep Enter=search while there's still no result.
        if (e.key === 'Enter' && !e.shiftKey && !loading && !result) {
            e.preventDefault();
            handleSearch();
        }
    }, [loading, result, handleSearch]);

    const portalEl = useMemo(() => {
        if (typeof document === 'undefined') return null;
        let el = document.getElementById('metadata-lookup-root');
        if (!el) {
            el = document.createElement('div');
            el.id = 'metadata-lookup-root';
            document.body.appendChild(el);
        }
        return el;
    }, []);

    // Data derived from the result. Calculated BEFORE the first `return`
    // conditional, because the `useMemo` below is a hook: by React's rules of
    // hooks it can't come after an early return. If it did, when
    // opening the modal (isOpen false→true) more hooks would be rendered than in the
    // render anterior → "Rendered more hooks than during the previous render".
    const sug = result?.suggested || {};
    const fieldEntries = Object.entries(sug);
    // L2: groups entries by relevance according to the result's Zotero type.
    // `Item Type` doesn't appear in the table (it's shown as a badge in the header).
    // If the type isn't recognized, everything goes to "other" (the table renders
    // as a single section, with no group header).
    const zoteroType = resolveZoteroType(sug['Item Type']);
    const { relevantEntries, otherEntries } = useMemo(() => {
        const rel = [], oth = [];
        for (const [k, v] of fieldEntries) {
            if (k === 'Item Type') continue;
            if (zoteroType && isFieldRelevantForType(k, zoteroType)) rel.push([k, v]);
            else oth.push([k, v]);
        }
        return { relevantEntries: rel, otherEntries: oth };
    }, [fieldEntries, zoteroType]);

    // Esc + focus-trap centralized in the canonical hook (before the early-return
    // to avoid introducing conditional hooks). We do NOT pass onConfirm: the Enter
    // for this modal is handled by handleKeyDown (Enter=search when there is no
    // resultat).
    useModalKeyboard({ isOpen, onClose, containerRef: panelRef, trapFocus: true });

    if (!isOpen || !portalEl) return null;

    // PR #5: format validation for identifiers. If the value is empty, the
    // validation doesn't apply (not all fields are mandatory). If it has
    // an invalid format, we show a hint below the input + block the search to
    // save the roundtrip.
    const vDoi = validateIdentifier('doi', doi);
    const vIsbn = validateIdentifier('isbn', isbn);
    const vArxiv = validateIdentifier('arxiv', arxivId);
    const vPmid = validateIdentifier('pmid', pmid);
    const vUrl = validateIdentifier('url', url);
    const allValid = vDoi.valid && vIsbn.valid && vArxiv.valid && vPmid.valid && vUrl.valid;
    const hasIdentifier = !!(doi.trim() || isbn.trim() || arxivId.trim() || pmid.trim() || url.trim());
    const canSearch = hasIdentifier && allValid;
    const inputCls = (valid) =>
        `px-2 py-1.5 text-sm rounded-md border bg-[var(--bg-primary)] outline-none transition-colors ${
            valid
                ? 'border-[var(--border-primary)] focus:border-[var(--gnosi-primary)]'
                : 'border-red-500 focus:border-red-600'
        }`;
    const hintCls = "text-[10px] text-red-500 mt-0.5";

    const allSelected = fieldEntries.length > 0 && fieldEntries.every(([k]) => selectedFields[k]);
    // Zotero-type label in the UI's active language (previously always ca-AD).
    const typeLabel = zoteroTypeLabel(zoteroType, i18n?.language);

    return ReactDOM.createPortal(
        <div
            className="fixed inset-0 z-[var(--z-modal)] flex items-start justify-center pt-16 bg-black/40"
            onKeyDown={handleKeyDown}
        >
            <div
                ref={panelRef}
                className="w-full max-w-3xl rounded-xl shadow-2xl border border-[var(--border-primary)] bg-[var(--bg-primary)] overflow-hidden max-h-[85vh] flex flex-col"
                role="dialog"
                aria-modal="true"
                aria-label={mode === 'create'
                    ? t('metadata_lookup.create_title', { defaultValue: 'Create from a source' })
                    : t('metadata_lookup.title', { defaultValue: 'Fill in metadata' })}
            >
                <div className="flex items-center gap-3 px-4 py-3 border-b border-[var(--border-secondary)] shrink-0">
                    <Search size={18} className="text-[var(--text-tertiary)]" />
                    <div className="flex-1 text-sm font-medium text-[var(--text-primary)]">
                        {mode === 'create'
                            ? t('metadata_lookup.create_title', { defaultValue: "Create from a source" })
                            : t('metadata_lookup.title', { defaultValue: "Fill in metadata" })}
                    </div>
                    <button
                        type="button"
                        onClick={onClose}
                        className="text-[var(--text-tertiary)] hover:text-[var(--text-primary)]"
                        title={t('common.close', { defaultValue: "Close" })}
                    >
                        <X size={18} />
                    </button>
                </div>

                <div className="px-4 py-3 border-b border-[var(--border-secondary)] grid grid-cols-2 gap-3 shrink-0">
                    <label className="flex flex-col gap-1">
                        <span className="text-xs font-semibold text-[var(--text-secondary)]">DOI</span>
                        <input
                            ref={firstInputRef}
                            type="text"
                            value={doi}
                            onChange={(e) => setDoi(e.target.value)}
                            placeholder="10.xxxx/xxxxx"
                            className={inputCls(vDoi.valid)}
                            aria-invalid={!vDoi.valid}
                        />
                        {!vDoi.valid && <span className={hintCls}>{vDoi.hint}</span>}
                    </label>
                    <label className="flex flex-col gap-1">
                        <span className="text-xs font-semibold text-[var(--text-secondary)]">ISBN</span>
                        <input
                            type="text"
                            value={isbn}
                            onChange={(e) => setIsbn(e.target.value)}
                            placeholder="978…"
                            className={inputCls(vIsbn.valid)}
                            aria-invalid={!vIsbn.valid}
                        />
                        {!vIsbn.valid && <span className={hintCls}>{vIsbn.hint}</span>}
                    </label>
                    <label className="flex flex-col gap-1">
                        <span className="text-xs font-semibold text-[var(--text-secondary)]">arXiv id</span>
                        <input
                            type="text"
                            value={arxivId}
                            onChange={(e) => setArxivId(e.target.value)}
                            placeholder="2103.00020"
                            className={inputCls(vArxiv.valid)}
                            aria-invalid={!vArxiv.valid}
                        />
                        {!vArxiv.valid && <span className={hintCls}>{vArxiv.hint}</span>}
                    </label>
                    <label className="flex flex-col gap-1">
                        <span className="text-xs font-semibold text-[var(--text-secondary)]">PMID</span>
                        <input
                            type="text"
                            value={pmid}
                            onChange={(e) => setPmid(e.target.value)}
                            placeholder="29083320"
                            className={inputCls(vPmid.valid)}
                            aria-invalid={!vPmid.valid}
                        />
                        {!vPmid.valid && <span className={hintCls}>{vPmid.hint}</span>}
                    </label>
                    <label className="flex flex-col gap-1">
                        <span className="text-xs font-semibold text-[var(--text-secondary)]">URL</span>
                        <input
                            type="text"
                            value={url}
                            onChange={(e) => setUrl(e.target.value)}
                            placeholder="https://…"
                            className={inputCls(vUrl.valid)}
                            aria-invalid={!vUrl.valid}
                        />
                        {!vUrl.valid && <span className={hintCls}>{vUrl.hint}</span>}
                    </label>
                </div>

                <div className="flex items-center gap-3 px-4 py-2 border-b border-[var(--border-secondary)] shrink-0">
                    <button
                        type="button"
                        onClick={handleSearch}
                        disabled={loading || !canSearch}
                        title={
                            !hasIdentifier
                                ? t('metadata_lookup.need_identifier', { defaultValue: "A DOI, ISBN, arXiv id, PMID or URL is required" })
                                : !allValid
                                    ? t('metadata_lookup.fix_invalid', { defaultValue: "Fix the fields in red before searching" })
                                    : ''
                        }
                        className="px-3 py-1.5 rounded-md bg-[var(--gnosi-primary)] text-white text-sm font-medium hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                    >
                        {loading && <Loader2 size={14} className="animate-spin" />}
                        {t('metadata_lookup.search', { defaultValue: "Search" })}
                    </button>
                    <input
                        ref={pdfInputRef}
                        type="file"
                        accept="application/pdf,.pdf"
                        className="hidden"
                        onChange={handlePdfUpload}
                    />
                    <button
                        type="button"
                        onClick={() => pdfInputRef.current?.click()}
                        disabled={loading}
                        className="px-3 py-1.5 rounded-md border border-[var(--border-primary)] text-[var(--text-secondary)] text-sm font-medium hover:bg-[var(--bg-hover)] disabled:opacity-50"
                    >
                        {t('metadata_lookup.from_pdf', { defaultValue: "Detect from a PDF" })}
                    </button>
                    {result?.source && (
                        <span className="text-xs text-[var(--text-tertiary)]">
                            {t('metadata_lookup.source_label', { defaultValue: "Source" })}: <strong className="text-[var(--text-secondary)]">{SOURCE_LABELS[result.source] || result.source}</strong>
                            {result.identifier && (
                                <> · <code className="text-[10px] bg-[var(--bg-secondary)] px-1 rounded">{result.identifier}</code></>
                            )}
                            {typeLabel && (
                                <> · {t('metadata_lookup.type_label', { defaultValue: "Type" })}: <strong className="text-[var(--text-secondary)]">{typeLabel}</strong></>
                            )}
                        </span>
                    )}
                </div>

                <div className="flex-1 overflow-y-auto">
                    {result && fieldEntries.length === 0 && !loading && (
                        <div className="px-4 py-8 text-center text-sm text-[var(--text-tertiary)]">
                            {result.error || t('metadata_lookup.no_data', { defaultValue: "No data found." })}
                        </div>
                    )}
                    {fieldEntries.length > 0 && (
                        <table className="w-full text-sm">
                            <thead className="sticky top-0 bg-[var(--bg-secondary)] text-xs text-[var(--text-secondary)] uppercase">
                                <tr>
                                    <th className="px-3 py-2 text-left w-8">
                                        <input
                                            type="checkbox"
                                            checked={allSelected}
                                            onChange={(e) => {
                                                const v = e.target.checked;
                                                const next = {};
                                                fieldEntries.forEach(([k]) => { next[k] = v; });
                                                setSelectedFields(next);
                                            }}
                                        />
                                    </th>
                                    <th className="px-3 py-2 text-left">{t('metadata_lookup.field', { defaultValue: "Field" })}</th>
                                    <th className="px-3 py-2 text-left">{t('metadata_lookup.current', { defaultValue: "Current" })}</th>
                                    <th className="px-3 py-2 text-left">{t('metadata_lookup.proposed', { defaultValue: "Proposed" })}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {(() => {
                                    // Local helper: a row with checkbox + current + proposed.
                                    const renderRow = ([k, v]) => {
                                        const current = currentMetadata?.[k];
                                        const currentStr = current == null || current === '' ? '' : String(current);
                                        const proposed = v == null ? '' : String(v);
                                        const isDifferent = currentStr !== proposed;
                                        return (
                                            <tr key={k} className="border-t border-[var(--border-secondary)] hover:bg-[var(--bg-hover)]">
                                                <td className="px-3 py-2">
                                                    <input
                                                        type="checkbox"
                                                        checked={!!selectedFields[k]}
                                                        onChange={(e) => setSelectedFields((prev) => ({ ...prev, [k]: e.target.checked }))}
                                                    />
                                                </td>
                                                <td className="px-3 py-2 font-medium text-[var(--text-primary)] align-top">{k}</td>
                                                <td className="px-3 py-2 text-[var(--text-tertiary)] align-top break-words max-w-xs">
                                                    {currentStr || <em className="opacity-60">{t('common.empty', { defaultValue: "Empty" })}</em>}
                                                </td>
                                                <td className={`px-3 py-2 align-top break-words max-w-md ${isDifferent ? 'text-[var(--text-primary)] font-medium' : 'text-[var(--text-tertiary)]'}`}>
                                                    {proposed}
                                                </td>
                                            </tr>
                                        );
                                    };
                                    // Case A: recognized type → two sections with separators.
                                    // Case B: no type or none relevant → flat list (compat).
                                    const grouped = zoteroType && relevantEntries.length > 0;
                                    return (
                                        <>
                                            {grouped && (
                                                <tr className="bg-[var(--bg-secondary)]/40">
                                                    <td colSpan={4} className="px-3 py-1.5 text-[11px] font-semibold uppercase text-[var(--text-secondary)] tracking-wide">
                                                        {t('metadata_lookup.relevant_for', { defaultValue: "Fields of the type" })}
                                                        <span className="ml-1 text-[var(--text-tertiary)] font-normal normal-case">({relevantEntries.length})</span>
                                                    </td>
                                                </tr>
                                            )}
                                            {relevantEntries.map(renderRow)}
                                            {grouped && otherEntries.length > 0 && (
                                                <tr className="bg-[var(--bg-secondary)]/40">
                                                    <td colSpan={4} className="px-3 py-1.5 text-[11px] font-semibold uppercase text-[var(--text-tertiary)] tracking-wide">
                                                        {t('metadata_lookup.other_fields', { defaultValue: "Other fields" })}
                                                        <span className="ml-1 font-normal normal-case">({otherEntries.length}) — {t('metadata_lookup.not_native', "the type doesn't carry them natively")}</span>
                                                    </td>
                                                </tr>
                                            )}
                                            {otherEntries.map(renderRow)}
                                        </>
                                    );
                                })()}
                            </tbody>
                        </table>
                    )}
                </div>

                <div className="px-4 py-3 border-t border-[var(--border-secondary)] flex items-center justify-end gap-2 shrink-0">
                    <button
                        type="button"
                        onClick={onClose}
                        className="px-3 py-1.5 rounded-md text-sm text-[var(--text-secondary)] hover:bg-[var(--bg-hover)]"
                    >
                        {t('common.cancel', { defaultValue: "Cancel" })}
                    </button>
                    <button
                        type="button"
                        onClick={handleApply}
                        disabled={!result || fieldEntries.length === 0}
                        className="px-3 py-1.5 rounded-md bg-[var(--gnosi-primary)] text-white text-sm font-medium hover:opacity-90 disabled:opacity-50 flex items-center gap-2"
                    >
                        <Check size={14} />
                        {t('metadata_lookup.apply', { defaultValue: "Apply selection" })}
                    </button>
                </div>
            </div>
        </div>,
        portalEl,
    );
};

export default MetadataLookupModal;
