"""Converts vault images referenced in an email body into inline
attachments with Content-ID, and builds the MIME tree shared by the senders.

The composer (BlockNote) inserts pasted images as
``<img src="/api/vault/assets/...">``. This URL only resolves within the local
Gnosi instance: if sent as-is, the recipient gets a broken image. Just before
sending, ``extract_vault_inline_images`` replaces each ``src`` with
``cid:<id>`` and returns the bytes so they travel as a ``multipart/related`` part
of the message (data-URIs are discarded: Gmail/Outlook strip them from the body).
"""

import email as email_lib
import html
import logging
import mimetypes
import re
import urllib.parse
import uuid
from email import encoders
from email.header import decode_header, make_header
from email.message import Message
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import NotRequired, TypedDict

from backend.services.context_vars import get_active_vault_path

log = logging.getLogger(__name__)


class InlineImage(TypedDict):
    filename: str
    content_type: str
    data: bytes
    content_id: str


class MimeAsset(TypedDict):
    data: bytes
    filename: NotRequired[str]
    content_type: NotRequired[str]


class MailCidReference(TypedDict):
    url: str
    message_id: str
    cid: str
    email: str | None
    folder: str | None


# src attribute with a URL (relative or absolute with host) pointing to /api/vault/assets/.
# Only `src=`: <a href> links to vault files are not inline images.
_VAULT_ASSET_SRC_RE = re.compile(
    r"""src=(["'])(?P<url>(?:https?://[^"']*?)?/api/vault/assets/[^"']+)\1""",
    re.IGNORECASE,
)

# src attribute pointing to a Content-ID: the quotedHtml of a reply/forward
# keeps the cid: from the original message (no MIME part in the new email).
_CID_SRC_RE = re.compile(
    r"""src=(["'])cid:(?P<cid>[^"']+)\1""",
    re.IGNORECASE,
)

# src attribute pointing to the /api/mail/messages/{id}/cid/{cid} endpoint: it's how the
# viewer (and the quotedHtml) reference the inline images of a received message
# for the composer to display them. The URL is self-contained (message, cid,
# email and folder in the query) — on send it becomes its own inline part.
_MAIL_CID_SRC_RE = re.compile(
    r"""src=(["'])(?P<url>(?:https?://[^"']*?)?/api/mail/messages/[^/"']+/cid/[^"']+)\1""",
    re.IGNORECASE,
)


def new_content_id() -> str:
    """Unique Content-ID for an inline part generated by Gnosi."""
    return f"{uuid.uuid4().hex}@gnosi.local"


def _resolve_asset_file(url: str, assets_root: Path) -> Path | None:
    """Resolves an asset URL to the file inside the active vault's ``Assets/``.

    Returns None if the path escapes Assets (traversal) or isn't a file.

    """
    rel = url.split("/api/vault/assets/", 1)[1]
    # HTML serializes & as &amp; and names with spaces are percent-encoded.
    rel = urllib.parse.unquote(html.unescape(rel))
    rel = rel.split("?", 1)[0].split("#", 1)[0]
    if not rel:
        return None
    candidate = (assets_root / rel).resolve()
    if not candidate.is_relative_to(assets_root):
        log.warning("Asset outside Assets/ ignored for inline rendering: %r", url)
        return None
    if not candidate.is_file():
        return None
    return candidate


def extract_vault_inline_images(body: str) -> tuple[str, list[InlineImage]]:
    """Replaces vault asset src attributes with cid: and returns the bytes.

    Args:
        body: HTML of the email body as it comes out of the composer.

    Returns:
        Tuple (new_body, inline_images) where inline_images is a list of dicts
        with filename, content_type, data and content_id. The same repeated URL
        reuses the same Content-ID. If an asset doesn't exist, isn't an
        image, or can't be read, its URL is left intact (sending is never blocked
        because of a missing asset).

    """
    if not body or "/api/vault/assets/" not in body:
        return body, []

    try:
        active_path = get_active_vault_path()
        if active_path is None:
            return body, []
        assets_root = (active_path / "Assets").resolve()
    except Exception as e:
        log.warning("Could not resolve Assets/ for the active vault: %s", e)
        return body, []

    images: list[InlineImage] = []
    cid_by_url: dict[str, str | None] = {}

    def _replace(match: re.Match[str]) -> str:
        url = match.group("url")
        if url not in cid_by_url:
            cid_by_url[url] = None
            asset = _resolve_asset_file(url, assets_root)
            if asset is None:
                log.warning("Inline image not found in the vault; preserving URL: %r", url)
            else:
                content_type = mimetypes.guess_type(asset.name)[0] or ""
                data = asset.read_bytes()
                if not content_type.startswith("image/"):
                    log.warning(
                        "Asset source is not an image (%s); preserving URL: %r", content_type, url
                    )
                elif not data:
                    # 0 bytes = likely a non-materialized OneDrive online-only file
                    log.warning("Asset is empty (possibly online-only); preserving URL: %r", url)
                else:
                    cid = new_content_id()
                    images.append(
                        {
                            "filename": asset.name,
                            "content_type": content_type,
                            "data": data,
                            "content_id": cid,
                        }
                    )
                    cid_by_url[url] = cid
        resolved_cid = cid_by_url[url]
        if resolved_cid is None:
            return match.group(0)
        quote = match.group(1)
        return f"src={quote}cid:{resolved_cid}{quote}"

    new_body = _VAULT_ASSET_SRC_RE.sub(_replace, body)
    return new_body, images


def find_cid_srcs(body: str) -> set[str]:
    """Content-IDs referenced as ``src="cid:..."`` in the body (without ``<>``)."""
    if not body or "cid:" not in body:
        return set()
    return {m.group("cid") for m in _CID_SRC_RE.finditer(body)}


def rewrite_cid_srcs(body: str, mapping: dict[str, str]) -> str:
    """Rewrites ``src="cid:old"`` → ``src="cid:new"`` according to the mapping.

    cids with no entry in the mapping (unrecoverable) are left intact:
    the recipient will see them broken just like before, but sending is never
    blocked and the others are not lost.

    """
    if not body or not mapping:
        return body

    def _replace(match: re.Match[str]) -> str:
        new_cid = mapping.get(match.group("cid"))
        if new_cid is None:
            return match.group(0)
        quote = match.group(1)
        return f"src={quote}cid:{new_cid}{quote}"

    return _CID_SRC_RE.sub(_replace, body)


def find_mail_cid_refs(body: str) -> list[MailCidReference]:
    """References to ``/api/mail/messages/{id}/cid/{cid}`` in the body's src attributes.

    Returns:
        List (order of appearance, unique URLs) of dicts with ``url`` (literal
        src, for rewriting it), ``message_id`` and ``cid`` (percent-
        decoded) and ``email``/``folder`` from the URL query (None if
        not present).

    """
    if not body or "/api/mail/messages/" not in body:
        return []
    refs: list[MailCidReference] = []
    seen: set[str] = set()
    for match in _MAIL_CID_SRC_RE.finditer(body):
        url = match.group("url")
        if url in seen:
            continue
        seen.add(url)
        parsed = urllib.parse.urlsplit(html.unescape(url))
        rest = parsed.path.split("/api/mail/messages/", 1)[1]
        message_id, _, cid = rest.partition("/cid/")
        if not message_id or not cid:
            continue
        query = urllib.parse.parse_qs(parsed.query)
        refs.append(
            {
                "url": url,
                "message_id": urllib.parse.unquote(message_id),
                "cid": urllib.parse.unquote(cid),
                "email": query.get("email", [None])[0],
                "folder": query.get("folder", [None])[0],
            }
        )
    return refs


def rewrite_mail_cid_srcs(body: str, mapping: dict[str, str]) -> str:
    """Rewrites ``src="<url /cid/>"`` → ``src="cid:nou"`` (mapping by literal URL)."""
    if not body or not mapping:
        return body

    def _replace(match: re.Match[str]) -> str:
        new_cid = mapping.get(match.group("url"))
        if new_cid is None:
            return match.group(0)
        quote = match.group(1)
        return f"src={quote}cid:{new_cid}{quote}"

    return _MAIL_CID_SRC_RE.sub(_replace, body)


def _decode_mime_words(value: str) -> str:
    """Decode a filename with RFC 2047 encoded-words (=?utf-8?...?=)."""
    try:
        return str(make_header(decode_header(value)))
    except Exception:
        return value


def extract_inline_parts_from_mime(raw_bytes: bytes, wanted_cids: set[str]) -> dict[str, MimeAsset]:
    """Extracts the parts with the requested Content-IDs from a raw MIME message.

    Args:
        raw_bytes: complete RFC 822 message (e.g. IMAP's FETCH BODY[]).
        wanted_cids: Content-IDs to look for (with or without ``<>``).

    Returns:
        Dict cid (without ``<>``) → {filename, content_type, data}. Parts
        without a decodable payload are omitted.

    """
    wanted = {c.strip("<>") for c in wanted_cids if c}
    if not wanted:
        return {}
    msg = email_lib.message_from_bytes(raw_bytes)
    parts: dict[str, MimeAsset] = {}
    for part in msg.walk():
        part_cid = (part.get("Content-ID") or "").strip("<>")
        if not part_cid or part_cid not in wanted or part_cid in parts:
            continue
        payload = part.get_payload(decode=True)
        if not isinstance(payload, bytes) or not payload:
            continue
        parts[part_cid] = {
            "filename": _decode_mime_words(part.get_filename() or "image"),
            "content_type": part.get_content_type() or "image/png",
            "data": payload,
        }
    return parts


def _file_part(content_type: str, data: bytes) -> MIMEBase:
    maintype, _, subtype = (content_type or "application/octet-stream").partition("/")
    part = MIMEBase(maintype or "application", subtype or "octet-stream")
    part.set_payload(data)
    encoders.encode_base64(part)
    return part


def build_mail_content(
    body: str,
    attachments: list[MimeAsset] | None = None,
    inline_images: list[InlineImage] | None = None,
) -> Message:
    """Builds the content's MIME tree (without sending headers).

    Structure: text → multipart/related(text + inline) if there are inline
    images → multipart/mixed(related|text + attachments) if there are attachments. The
    senders (Gmail, SMTP) add From/To/Subject/... on top.

    Args:
        body: message body (HTML if it starts with "<", plain text otherwise).
        attachments: dicts with filename, content_type and data.
        inline_images: dicts from ``extract_vault_inline_images``.

    Returns:
        Root email.message.Message of the content.

    """
    subtype = "html" if body.strip().startswith("<") else "plain"
    content: Message = MIMEText(body, subtype, "utf-8")

    if inline_images:
        related = MIMEMultipart("related")
        related.attach(content)
        for img in inline_images:
            part = _file_part(img.get("content_type"), img["data"])
            part.add_header("Content-ID", f"<{img['content_id']}>")
            part.add_header(
                "Content-Disposition",
                "inline",
                filename=img.get("filename", "image"),
            )
            related.attach(part)
        content = related

    if attachments:
        mixed = MIMEMultipart("mixed")
        mixed.attach(content)
        for att in attachments:
            part = _file_part(att.get("content_type") or "application/octet-stream", att["data"])
            part.add_header(
                "Content-Disposition",
                "attachment",
                filename=att.get("filename", "attachment"),
            )
            mixed.attach(part)
        content = mixed

    return content
