"""Compatibility facade for the typed Notion view-recreation domain."""

from typing import (
    Any as Any,
    Dict as Dict,
    List as List,
    Optional as Optional,
    Tuple as Tuple,
)

from backend.domains.notion.view_recreator import (
    _DB_RE,
    _DS_ENTRY_RE,
    _DS_NAME_RE,
    _HEADING_RE,
    _NS,
    _PAGE_ID_RE,
    _VIEW_RE,
    _advanced_filters,
    _canonical_view_payload,
    _filter_value,
    _parse_view_json,
    _scalar,
    _strip_icon,
    _uid,
    _value_mentions_host_page,
    build_gnosi_view,
    deduplicate_view_definitions,
    is_contextual_view,
    json as json,
    map_simple_filter,
    parse_mcp_page,
    parse_mcp_view,
    parse_mcp_views,
    re as re,
    recreate_views_for_page,
    resolve_filter_field,
    uuid as uuid,
    view_embed,
    view_identity,
)

__all__ = [
    "Any",
    "Dict",
    "List",
    "Optional",
    "Tuple",
    "build_gnosi_view",
    "deduplicate_view_definitions",
    "is_contextual_view",
    "json",
    "map_simple_filter",
    "parse_mcp_page",
    "parse_mcp_view",
    "parse_mcp_views",
    "re",
    "recreate_views_for_page",
    "resolve_filter_field",
    "uuid",
    "view_embed",
    "view_identity",
]
