"""Compatibility facade for the typed Notion importer domain."""

from typing import (
    Any as Any,
    Callable as Callable,
    Dict as Dict,
    Iterable as Iterable,
    List as List,
    Optional as Optional,
)

from backend.domains.notion.importer import (
    NOTION_API,
    NOTION_VERSION,
    READ_ONLY_TYPES,
    NotionClient,
    _COLOR_MAP as _COLOR_MAP,
    _GNOSI_NS as _GNOSI_NS,
    _PROP_TYPE_MAP as _PROP_TYPE_MAP,
    _color as _color,
    _emoji_icon as _emoji_icon,
    _file_url as _file_url,
    _page_title as _page_title,
    _plain_title as _plain_title,
    block_to_md,
    blocks_to_md,
    gnosi_id_for,
    map_database_schema,
    map_property_schema,
    page_id_for,
    page_to_values,
    rich_text_to_md,
    table_id_for,
    time as time,
    uuid as uuid,
    value_to_gnosi,
)

__all__ = [
    "Any",
    "Callable",
    "Dict",
    "Iterable",
    "List",
    "NOTION_API",
    "NOTION_VERSION",
    "READ_ONLY_TYPES",
    "NotionClient",
    "Optional",
    "block_to_md",
    "blocks_to_md",
    "gnosi_id_for",
    "map_database_schema",
    "map_property_schema",
    "page_id_for",
    "page_to_values",
    "rich_text_to_md",
    "table_id_for",
    "time",
    "uuid",
    "value_to_gnosi",
]
