#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Reverse Visual Sync: Markdown -> Notion
---------------------------------------
Scans local Markdown files for embedded images/diagrams and safe-appends them
to the corresponding Notion Page as Image Blocks.

SAFETY PROTOCOL:
1. READ-ONLY TEXT: Never modifies existing Notion blocks.
2. APPEND-ONLY: Adds new images to the bottom of the page.
3. IDEMPOTENCY: Uses a local hash registry (visual_sync_registry.json) to avoid duplicates.

USAGE:
    python reverse_visual_sync.py --dir "out/markdown_backup"
"""

import os
import re
import sys
import json
import hashlib
import argparse
import logging
from pathlib import Path
from typing import List, Dict, Optional, Tuple

# Optional Cloudinary Import
try:
    import cloudinary
    import cloudinary.uploader
    import cloudinary.api
except ImportError:
    cloudinary = None

# Import Notion Client and Config
# Ensuring we can find the 'pipeline' and 'config' modules if running from root
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from notion_client import Client
from config.env_config import get_env
from config.logger_config import setup_logging

# Setup Logging
setup_logging()
log = logging.getLogger(__name__)

# Constants
REGISTRY_FILE = "visual_sync_registry.json"
SUPPORTED_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".svg", ".excalidraw"}

class ReverseSyncManager:
    def __init__(self, directory: str, dry_run: bool = False):
        self.root_dir = Path(directory)
        self.dry_run = dry_run
        self.registry_path = self.root_dir / REGISTRY_FILE
        self.registry = self._load_registry()
        
        # Initialize Notion Client
        token = get_env("NOTION_TOKEN", required=False)
        if not token:
            log.error("❌ NOTION_TOKEN not found in environment variables.")
            if not dry_run:
                sys.exit(1)
            else:
                log.warning("⚠️ Running in Dry Run mode without token.")
        
        self.notion = Client(auth=token) if token else None

    def _load_registry(self) -> Dict:
        """Loads the idempotency registry from JSON."""
        if self.registry_path.exists():
            try:
                with open(self.registry_path, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception as e:
                log.warning(f"⚠️ Could not load registry: {e}. Starting fresh.")
        return {}

    def _save_registry(self):
        """Saves current registry to JSON."""
        if self.dry_run:
            return
        
        try:
            with open(self.registry_path, "w", encoding="utf-8") as f:
                json.dump(self.registry, f, indent=2, ensure_ascii=False)
        except Exception as e:
            log.error(f"❌ Failed to save registry: {e}")

    def calculate_file_hash(self, file_path: Path) -> str:
        """Calculates MD5 hash of a file for idempotency."""
        hash_md5 = hashlib.md5()
        try:
            with open(file_path, "rb") as f:
                for chunk in iter(lambda: f.read(4096), b""):
                    hash_md5.update(chunk)
            return hash_md5.hexdigest()
        except FileNotFoundError:
            return None

    def extract_page_id(self, file_path: Path, content: str) -> Optional[str]:
        """
        Extracts Notion Page ID from filename or frontmatter.
        Priority:
        1. Filename: "My Note [32-char-ID].md"
        2. Frontmatter: "url: https://notion.so/..." or "id: ..."
        """
        # 1. Try Filename (most reliable if generated by our backup script)
        # Looking for 32 hex chars inside brackets
        match = re.search(r'\[([0-9a-fA-F-]{32,36})\]', file_path.name)
        if match:
            # Normalize to 32 chars (remove dashes) or keep dashes?
            # Notion API accepts dashed or undashed.
            return match.group(1)

        # 2. Try Frontmatter (basic parsing)
        # We look for `url: "..."` or `notion_url: "..."`
        # This is a fallback and might be fragile without a yaml parser, 
        # but avoiding extra libs for now.
        frontmatter_match = re.search(r'^---\s+(.*?)\s+---', content, re.DOTALL)
        if frontmatter_match:
            fm_text = frontmatter_match.group(1)
            # Look for url: https://www.notion.so/{ID}
            # Handles:
            # - https://www.notion.so/32charID
            # - https://www.notion.so/workspace/Page-Title-32charID
            url_match = re.search(r'url:\s*"?https://.*\b([a-fA-F0-9]{32})"?', fm_text)
            if url_match:
                return url_match.group(1)

        return None

    def find_local_images(self, content: str, parent_dir: Path) -> List[Path]:
        """
        Finds local image references in Markdown.
        Supports:
        - Standard: ![alt](path/to/image.png)
        - Obsidian/Wiki: ![[image.png]]
        """
        found_images = []
        
        # 1. Standard Markdown: ![...](...)
        # Regex captures: group(1)=Alt, group(2)=Path
        std_matches = re.findall(r'!\[.*?\]\((.*?)\)', content)
        for img_path_str in std_matches:
            if img_path_str.startswith("http") or "notion.so" in img_path_str:
                continue # Skip remote images
            
            # Resolve relative path
            # Assuming paths are relative to the markdown file location
            full_path = (parent_dir / img_path_str).resolve()
            if full_path.exists() and full_path.suffix.lower() in SUPPORTED_EXTENSIONS:
                found_images.append(full_path)

        # 2. Wiki Links: ![[...]]
        # Regex captures: group(1)=Filename
        wiki_matches = re.findall(r'!\[\[(.*?)\]\]', content)
        for img_name in wiki_matches:
            # Obsidian often just uses the filename. 
            # We assume the image is in the same folder or a specific assets folder.
            # For this script, lets check the same folder first.
            
            # Pipe handling for aliases ![[image.png|100]]
            clean_name = img_name.split('|')[0]
            
            full_path = (parent_dir / clean_name).resolve()
            if full_path.exists() and full_path.suffix.lower() in SUPPORTED_EXTENSIONS:
                found_images.append(full_path)
            
            # TODO: Add recursion or specific 'assets' folder check if needed
            
        return list(set(found_images)) # Deduplicate

    def upload_image_to_host(self, file_path: Path) -> str:
        """
        Uploads image to Cloudinary if configured, otherwise uses placeholder.
        """
        cloudinary_url = get_env("CLOUDINARY_URL", required=False)
        
        if cloudinary_url and cloudinary:
            # Configure implies environment variable CLOUDINARY_URL is handled by library 
            # or we pass it explicitly. The Cloudinary Py library auto-reads CLOUDINARY_URL 
            # if present in os.environ, but we can also set it manually if needed.
            if not cloudinary.config().cloud_name:
                # If not auto-configured, try parsing manually (if format is cloudinary://...)
                # But typically setting os.environ["CLOUDINARY_URL"] is enough.
                pass

            try:
                log.info(f"   ☁️ Uploading to Cloudinary: {file_path.name}")
                if self.dry_run:
                    return f"https://res.cloudinary.com/demo/image/upload/{file_path.name}"
                
                # Upload
                response = cloudinary.uploader.upload(str(file_path), use_filename=True, unique_filename=False, folder="digital_brain_visuals")
                secure_url = response.get("secure_url")
                
                if secure_url:
                    log.info(f"   ✅ Uploaded: {secure_url}")
                    return secure_url
                else:
                    raise ValueError("Cloudinary response missing 'secure_url'")
                    
            except Exception as e:
                log.error(f"   ❌ Cloudinary Upload Error: {e}")
                # Fallback to placeholder? Or raise?
                # Raising ensures we don't sync broken links
                raise e
        else:
            log.warning(f"⚠️ Cloudinary not configured or library missing. Using Mock URL for: {file_path.name}")
            return f"https://placehold.co/600x400?text={file_path.name}"

    def sync_to_notion(self, page_id: str, image_url: str, image_path: Path):
        """Appends the image block to the Notion Page."""
        if self.dry_run:
            log.info(f"   [DRY RUN] Would append image block to {page_id}")
            return

        block_child = {
            "object": "block",
            "type": "image",
            "image": {
                "type": "external",
                "external": {
                    "url": image_url
                }
            }
        }
        
        # Add a caption with the original filename for reference
        # caption is optional, but helpful
        block_child["image"]["caption"] = [
            {"type": "text", "text": {"content": f"Synced from: {image_path.name}"}}
        ]

        try:
            self.notion.blocks.children.append(
                block_id=page_id,
                children=[block_child]
            )
            log.info(f"   ✅ Successfully appended to Notion Page {page_id}")
        except Exception as e:
            log.error(f"   ❌ Failed to append block: {e}")
            raise e

    def process(self):
        log.info(f"📂 Scanning directory: {self.root_dir}")
        if not self.root_dir.exists():
            log.error("Directory does not exist.")
            return

        processed_files = 0
        synced_images = 0

        for file_path in self.root_dir.glob("*.md"):
            processed_files += 1
            try:
                content = file_path.read_text(encoding="utf-8")
                
                # 1. Identity Page
                page_id = self.extract_page_id(file_path, content)
                if not page_id:
                    # log.debug(f"Skipping {file_path.name}: No Page ID found.")
                    continue

                # 2. Find Images
                images = self.find_local_images(content, file_path.parent)
                if not images:
                    continue

                # 3. Process Images
                for img_path in images:
                    img_hash = self.calculate_file_hash(img_path)
                    if not img_hash:
                        continue

                    # IDEMPOTENCY CHECK
                    # We check if THIS image hash has been uploaded for THIS page_id
                    # Registry structure: { "page_id_1": ["hashA", "hashB"], ... }
                    page_registry = self.registry.get(page_id, [])
                    
                    if img_hash in page_registry:
                        # Already synced
                        continue

                    log.info(f"🔄 Syncing new visual: {img_path.name} -> Page {page_id}")
                    
                    # Upload
                    try:
                        public_url = self.upload_image_to_host(img_path)
                        
                        # Sync
                        self.sync_to_notion(page_id, public_url, img_path)
                        
                        # Update Registry
                        if not self.dry_run:
                            if page_id not in self.registry:
                                self.registry[page_id] = []
                            self.registry[page_id].append(img_hash)
                            synced_images += 1
                            
                    except Exception as e:
                        log.error(f"   Failed to sync {img_path.name}: {e}")

            except Exception as e:
                log.error(f"Error reading {file_path.name}: {e}")

        self._save_registry()
        log.info(f"✨ DONE. Scanned {processed_files} files. Synced {synced_images} new images.")

def main():
    parser = argparse.ArgumentParser(description="Reverse Visual Sync")
    parser.add_argument("--dir", default="out/markdown_backup", help="Path to Markdown folder")
    parser.add_argument("--dry-run", action="store_true", help="Simulate without uploading")
    
    args = parser.parse_args()
    
    manager = ReverseSyncManager(args.dir, args.dry_run)
    manager.process()

if __name__ == "__main__":
    main()
