import { tableInputs } from './tableInputs';
import type { VaultTableProps } from './types';
import { useTableActions } from './useTableActions';
import { useTableAggregation } from './useTableAggregation';
import { useTableClipboard } from './useTableClipboard';
import { useTableColumnInteractions } from './useTableColumnInteractions';
import { useTableColumns } from './useTableColumns';
import { useTableCreate } from './useTableCreate';
import { useTableCursor } from './useTableCursor';
import { useTableData } from './useTableData';
import { useTableEntry } from './useTableEntry';
import { useTableIdentity } from './useTableIdentity';
import { useTableInput } from './useTableInput';
import { useTableKeyboard } from './useTableKeyboard';
import { useTableMedia } from './useTableMedia';
import { useTableNavigation } from './useTableNavigation';
import { useTableOptimistic } from './useTableOptimistic';
import { useTableOptions } from './useTableOptions';
import { useTablePlugins } from './useTablePlugins';
import { useTableResources } from './useTableResources';
import { useTableRows } from './useTableRows';
import { useTableSave } from './useTableSave';
import { useTableSelection } from './useTableSelection';
import { useTableState } from './useTableState';
import { useTableValues } from './useTableValues';
export function useTableController(props: VaultTableProps) {
  const inputs = tableInputs(props);
  const identity = useTableIdentity(inputs);
  const withIdentity = { ...inputs, ...identity };
  const optimistic = useTableOptimistic(withIdentity);
  const withOptimistic = { ...withIdentity, ...optimistic };
  const state = useTableState(withOptimistic);
  const withState = { ...withOptimistic, ...state };
  const plugins = useTablePlugins(withState);
  const withPlugins = { ...withState, ...plugins };
  const entry = useTableEntry(withPlugins);
  const withEntry = { ...withPlugins, ...entry };
  const data = useTableData(withEntry);
  const withData = { ...withEntry, ...data };
  const selection = useTableSelection(withData);
  const withSelection = { ...withData, ...selection };
  const rows = useTableRows(withSelection);
  const withRows = { ...withSelection, ...rows };
  const columns = useTableColumns(withRows);
  const withColumns = { ...withRows, ...columns };
  const navigation = useTableNavigation(withColumns);
  const withNavigation = { ...withColumns, ...navigation };
  const columnInteractions = useTableColumnInteractions(withNavigation);
  const withColumnInteractions = { ...withNavigation, ...columnInteractions };
  const resources = useTableResources(withColumnInteractions);
  const withResources = { ...withColumnInteractions, ...resources };
  const save = useTableSave(withResources);
  const withSave = { ...withResources, ...save };
  const create = useTableCreate(withSave);
  const withCreate = { ...withSave, ...create };
  const options = useTableOptions(withCreate);
  const withOptions = { ...withCreate, ...options };
  const input = useTableInput(withOptions);
  const withInput = { ...withOptions, ...input };
  const values = useTableValues(withInput);
  const withValues = { ...withInput, ...values };
  const media = useTableMedia(withValues);
  const withMedia = { ...withValues, ...media };
  const clipboard = useTableClipboard(withMedia);
  const withClipboard = { ...withMedia, ...clipboard };
  const cursor = useTableCursor(withClipboard);
  const withCursor = { ...withClipboard, ...cursor };
  const keyboard = useTableKeyboard(withCursor);
  const withKeyboard = { ...withCursor, ...keyboard };
  const actions = useTableActions(withKeyboard);
  const withActions = { ...withKeyboard, ...actions };
  const aggregation = useTableAggregation(withActions);
  const withAggregation = { ...withActions, ...aggregation };
  return withAggregation;
}
export type TableController = ReturnType<typeof useTableController>;
