import asyncio
import logging
from fastapi import APIRouter, HTTPException, Depends
from typing import Dict, Any
from backend.services.graph_service import GraphService
from backend.services.workspace_service import require_role
from backend.utils.errors import safe_error_detail
from pydantic import BaseModel
from typing import Dict, Any, Optional

log = logging.getLogger(__name__)

router = APIRouter()

class SuggestionRequest(BaseModel):
    source_id: str
    target_id: str
    reason: Optional[str] = None

@router.get("/graph")
async def get_vault_graph() -> Dict[str, Any]:
    """
    Returns the unified Vault graph (4 layers + pages + suggestions)
    generated by the GraphService.
    """
    try:
        # build_unified_graph does an rglob over the vault and layout computation with igraph
        # — can take seconds. Off-thread to avoid freezing the event loop and
        # blocking all other requests.
        service = GraphService()
        graph_data = await asyncio.to_thread(service.build_unified_graph)
        return graph_data
    except Exception as e:
        log.exception(f"Error generating the vault graph: {e}")
        raise HTTPException(status_code=500, detail=safe_error_detail(e, context="GET /api/graph"))

@router.post("/accept-suggestion", dependencies=[Depends(require_role("editor"))])
async def accept_suggestion(req: SuggestionRequest) -> Dict[str, Any]:
    """
    Accepts a suggested AI connection and saves it to the .md file frontmatter.
    """
    try:
        service = GraphService()
        result = service.accept_suggestion(req.source_id, req.target_id, reason=req.reason)
        if not result["success"]:
            raise HTTPException(status_code=400, detail=result["message"])
        return result
    except HTTPException:
        raise
    except Exception as e:
        log.exception(f"Error accepting suggestion: {e}")
        raise HTTPException(status_code=500, detail=safe_error_detail(e, context="POST /api/accept-suggestion"))
