vault_migration.settings:
  type: config_object
  label: 'Vault Bridge settings'
  mapping:
    databases:
      type: mapping
      label: 'Databases per bundle'
      mapping:
        '*':
          type: string
          label: 'Database ID'
    columns:
      type: mapping
      label: 'Column names and translation settings'
      mapping:
        content_key_base:
          type: string
          label: 'Content_key (base) property'
        content_key_formula:
          type: string
          label: 'Formula Content_key property'
        original_content_key_rollup:
          type: string
          label: 'Original Content_key rollup'
        original_rel:
          type: string
          label: 'Original relation property'
        lang:
          type: string
          label: 'Language property'
        status:
          type: string
          label: 'Status property'
        title:
          type: string
          label: 'Title property'
        status_published_value:
          type: string
          label: 'Published value for status (case-insensitive)'
        field_map:
          type: mapping
          label: 'Field mappings per bundle'
          mapping:
            '*':
              type: mapping
              label: 'Drupal field map'
              mapping:
                '*':
                  type: string
                  label: 'Drupal field machine name'
    sync:
      type: mapping
      label: 'Sync settings'
      mapping:
        batch_size:
          type: integer
          label: 'Flush batch size'
