"""Static source catalog responsibility: catalog common."""

from __future__ import annotations

import ast
import re
from pathlib import Path

GENERATED_NOTICE = (
    "<!-- Generated by pipeline/skills/technical_documentation/scripts/generate.py. "
    "Do not edit manually. -->"
)


GENERATE_COMMAND = "python pipeline/skills/technical_documentation/scripts/generate.py"


SOURCE_SUFFIXES = {".js", ".jsx", ".ts", ".tsx"}


PUBLIC_SOURCE_BASE = "https://github.com/ismigar/Gnosi/blob/main"


TEST_NAME_RE = re.compile(r"(?:^test_.*\.py$|.*\.(?:test|spec)\.(?:js|jsx|ts|tsx)$)")


SECRET_NAME_RE = re.compile(
    r"(?:API_?KEY|BEARER|CREDENTIAL|PASSWORD|PRIVATE|SECRET|TOKEN)", re.IGNORECASE
)


EXCLUDED_FILE_PARTS = {
    ".auth",
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tmp",
    ".venv",
    ".venv-python",
    ".vite",
    "__pycache__",
    "coverage",
    "dist",
    "dist-python",
    "local_data",
    "logs",
    "node_modules",
    "playwright-report",
    "python-build",
    "private_skills",
    "sandbox",
    "secrets",
    "test-results",
    "vendor",
}


EXCLUDED_FILE_NAMES = {
    "zotero_db_config.json",
}


def relative_posix(path: Path, root: Path) -> str:
    """Return a stable repository-relative POSIX path."""
    return path.resolve().relative_to(root.resolve()).as_posix()


def read_text(path: Path) -> str:
    """Read UTF-8 source while tolerating isolated replacement characters."""
    return path.read_text(encoding="utf-8", errors="replace")


def markdown_cell(value: object) -> str:
    """Escape a value for a compact Markdown table cell."""
    text = " ".join(str(value).split())
    return text.replace("|", "\\|") or "—"


def source_link(source: str, line: int | None = None) -> str:
    """Build a public repository link to application source."""
    anchor = f"#L{line}" if line else ""
    label = f"`{source}:{line}`" if line else f"`{source}`"
    return f"[{label}]({PUBLIC_SOURCE_BASE}/{source}{anchor})"


def generated_header(title: str, description: str) -> list[str]:
    """Return the common header for generated reference pages."""
    return [
        GENERATED_NOTICE,
        "",
        f"# {title}",
        "",
        description,
        "",
        f"Regenerate with `{GENERATE_COMMAND}`.",
        "",
    ]


def expression_name(node: ast.AST) -> str:
    """Return a dotted name for a simple Python expression."""
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        parent = expression_name(node.value)
        return f"{parent}.{node.attr}" if parent else node.attr
    return ""


def safe_unparse(node: ast.AST | None, limit: int = 90) -> str:
    """Render a short AST expression without evaluating it."""
    if node is None:
        return "—"
    try:
        value = ast.unparse(node)
    except (AttributeError, ValueError):
        return "dynamic"
    value = " ".join(value.split())
    value = re.sub(r"\blambda\s+:", "lambda:", value)
    return value if len(value) <= limit else f"{value[: limit - 1]}…"


def constant_string(node: ast.AST | None, default: str = "") -> str:
    """Return a string constant or a safe marker for a dynamic expression."""
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return default


def keyword(call: ast.Call, name: str) -> ast.AST | None:
    """Return a named call keyword value."""
    for item in call.keywords:
        if item.arg == name:
            return item.value
    return None


def string_list(node: ast.AST | None) -> tuple[str, ...]:
    """Return constant strings from a list or tuple expression."""
    if not isinstance(node, (ast.List, ast.Tuple, ast.Set)):
        return ()
    return tuple(
        item.value
        for item in node.elts
        if isinstance(item, ast.Constant) and isinstance(item.value, str)
    )


def join_url_paths(*parts: str) -> str:
    """Join URL path fragments without changing path parameters."""
    nonempty = [part.strip("/") for part in parts if part and part != "/"]
    return f"/{'/'.join(nonempty)}" if nonempty else "/"


def first_doc_line(
    node: ast.AsyncFunctionDef | ast.FunctionDef | ast.ClassDef | ast.Module,
    fallback: str,
) -> str:
    """Return the first useful line of a Python docstring."""
    doc = ast.get_docstring(node, clean=True)
    if not doc:
        return fallback.replace("_", " ").strip().capitalize()
    for line in doc.splitlines():
        if line.strip():
            return line.strip()
    return fallback.replace("_", " ").strip().capitalize()


def python_files(root: Path, *, include_tests: bool = True) -> list[Path]:
    """Return owned Python files with generated and cache trees excluded."""
    files: list[Path] = []
    for path in root.rglob("*.py"):
        parts = set(path.parts)
        if parts.intersection(EXCLUDED_FILE_PARTS):
            continue
        if not include_tests and ("tests" in parts or TEST_NAME_RE.match(path.name)):
            continue
        files.append(path)
    return sorted(files)


def frontend_files(root: Path, *, include_tests: bool = True) -> list[Path]:
    """Return owned frontend source files, excluding vendor and build output."""
    files: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file() or path.suffix not in SOURCE_SUFFIXES:
            continue
        parts = set(path.parts)
        if parts.intersection(EXCLUDED_FILE_PARTS):
            continue
        if not include_tests and TEST_NAME_RE.match(path.name):
            continue
        files.append(path)
    return sorted(files)


def is_owned_inventory_file(path: Path) -> bool:
    """Return whether a file belongs in high-level owned-source counts."""
    if not path.is_file() or path.name.startswith(".") or path.name in EXCLUDED_FILE_NAMES:
        return False
    if set(path.parts).intersection(EXCLUDED_FILE_PARTS):
        return False
    return path.suffix not in {".oxt", ".pyc", ".pyo"}
