#!/usr/bin/env python3
"""Generate deterministic source catalogs for the Gnosi engineering portal."""

from __future__ import annotations

import argparse
import ast
import json
import logging
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


log = logging.getLogger(__name__)

GENERATED_NOTICE = (
    "<!-- Generated by pipeline/skills/technical_documentation/scripts/generate.py. "
    "Do not edit manually. -->"
)
GENERATE_COMMAND = "python pipeline/skills/technical_documentation/scripts/generate.py"
HTTP_METHODS = {
    "delete",
    "get",
    "head",
    "options",
    "patch",
    "post",
    "put",
    "trace",
    "websocket",
}
SOURCE_SUFFIXES = {".js", ".jsx", ".ts", ".tsx"}
PUBLIC_SOURCE_BASE = "https://github.com/ismigar/Gnosi/blob/main"
TEST_NAME_RE = re.compile(r"(?:^test_.*\.py$|.*\.(?:test|spec)\.(?:js|jsx|ts|tsx)$)")
SECRET_NAME_RE = re.compile(
    r"(?:API_?KEY|BEARER|CREDENTIAL|PASSWORD|PRIVATE|SECRET|TOKEN)", re.IGNORECASE
)
EXCLUDED_FILE_PARTS = {
    ".auth",
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".venv",
    ".venv-python",
    "__pycache__",
    "coverage",
    "dist",
    "dist-python",
    "local_data",
    "logs",
    "node_modules",
    "playwright-report",
    "python-build",
    "secrets",
    "test-results",
    "vendor",
}
EXCLUDED_FILE_NAMES = {
    "zotero_db_config.json",
}
FRONTEND_ENV_RE = re.compile(r"\b(?:import\.meta|process)\.env\.([A-Z][A-Z0-9_]*)")
FRONTEND_API_RE = re.compile(r"['\"](/api/[A-Za-z0-9_?&=./:{}*+%-]+)['\"]")
ROUTE_RE = re.compile(
    r'<Route\s+path\s*=\s*["\']([^"\']+)["\']\s+element\s*=\s*\{\s*<([A-Za-z_$][\w$]*)'
)
STATIC_IMPORT_RE = re.compile(
    r"\bimport\s+(?!type\b)([^;]+?)\s+from\s+['\"]([^'\"]+)['\"]"
)
LAZY_IMPORT_RE = re.compile(
    r"const\s+([A-Za-z_$][\w$]*)\s*=\s*lazy\(.*?import\(['\"]([^'\"]+)['\"]\)",
    re.DOTALL,
)


@dataclass(frozen=True)
class RouterRegistration:
    """Describe one router attached to the FastAPI application."""

    module: str
    prefix: str
    tags: tuple[str, ...]
    line: int
    source: str = "backend/server.py"


@dataclass(frozen=True)
class RouteOperation:
    """Describe one statically discovered FastAPI route operation."""

    method: str
    path: str
    handler: str
    module: str
    line: int
    tags: tuple[str, ...]
    guards: str
    summary: str


@dataclass(frozen=True)
class RouterConfiguration:
    """Describe static prefix, tags, and guards owned by an APIRouter."""

    prefix: str = ""
    tags: tuple[str, ...] = ()
    guard: str = ""


@dataclass(frozen=True)
class EnvironmentReference:
    """Describe one environment-variable reference without exposing its value."""

    name: str
    default: str
    source: str
    line: int
    runtime: str


@dataclass(frozen=True)
class FrontendRoute:
    """Describe a literal JSX route and its outer element's source."""

    path: str
    component: str
    source: str


def find_app_root(start: Path) -> Path:
    """Return the application root containing the backend and frontend trees."""
    for candidate in (start.resolve(), *start.resolve().parents):
        if (candidate / "backend").is_dir() and (candidate / "frontend").is_dir():
            return candidate
    raise RuntimeError(f"Could not locate the Gnosi application root from {start}")


def find_project_root(start: Path) -> Path:
    """Return the repository root that may own private development directives.

    Canonical generation must not change merely because the checkout happens
    to live below a private workspace repository. External memory can still be
    supplied explicitly with ``--project-root`` for local audits.
    """
    return find_app_root(start)


def relative_posix(path: Path, root: Path) -> str:
    """Return a stable repository-relative POSIX path."""
    return path.resolve().relative_to(root.resolve()).as_posix()


def read_text(path: Path) -> str:
    """Read UTF-8 source while tolerating isolated replacement characters."""
    return path.read_text(encoding="utf-8", errors="replace")


def markdown_cell(value: object) -> str:
    """Escape a value for a compact Markdown table cell."""
    text = " ".join(str(value).split())
    return text.replace("|", "\\|") or "—"


def source_link(source: str, line: int | None = None) -> str:
    """Build a public repository link to application source."""
    anchor = f"#L{line}" if line else ""
    label = f"`{source}:{line}`" if line else f"`{source}`"
    return f"[{label}]({PUBLIC_SOURCE_BASE}/{source}{anchor})"


def generated_header(title: str, description: str) -> list[str]:
    """Return the common header for generated reference pages."""
    return [
        GENERATED_NOTICE,
        "",
        f"# {title}",
        "",
        description,
        "",
        f"Regenerate with `{GENERATE_COMMAND}`.",
        "",
    ]


def expression_name(node: ast.AST) -> str:
    """Return a dotted name for a simple Python expression."""
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        parent = expression_name(node.value)
        return f"{parent}.{node.attr}" if parent else node.attr
    return ""


def safe_unparse(node: ast.AST | None, limit: int = 90) -> str:
    """Render a short AST expression without evaluating it."""
    if node is None:
        return "—"
    try:
        value = ast.unparse(node)
    except (AttributeError, ValueError):
        return "dynamic"
    value = " ".join(value.split())
    value = re.sub(r"\blambda\s+:", "lambda:", value)
    return value if len(value) <= limit else f"{value[: limit - 1]}…"


def constant_string(node: ast.AST | None, default: str = "") -> str:
    """Return a string constant or a safe marker for a dynamic expression."""
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return default


def keyword(call: ast.Call, name: str) -> ast.AST | None:
    """Return a named call keyword value."""
    for item in call.keywords:
        if item.arg == name:
            return item.value
    return None


def string_list(node: ast.AST | None) -> tuple[str, ...]:
    """Return constant strings from a list or tuple expression."""
    if not isinstance(node, (ast.List, ast.Tuple, ast.Set)):
        return ()
    return tuple(
        item.value
        for item in node.elts
        if isinstance(item, ast.Constant) and isinstance(item.value, str)
    )


def join_url_paths(*parts: str) -> str:
    """Join URL path fragments without changing path parameters."""
    nonempty = [part.strip("/") for part in parts if part and part != "/"]
    return f"/{'/'.join(nonempty)}" if nonempty else "/"


def first_doc_line(node: ast.AST, fallback: str) -> str:
    """Return the first useful line of a Python docstring."""
    doc = ast.get_docstring(node, clean=True)
    if not doc:
        return fallback.replace("_", " ").strip().capitalize()
    for line in doc.splitlines():
        if line.strip():
            return line.strip()
    return fallback.replace("_", " ").strip().capitalize()


def python_files(root: Path, *, include_tests: bool = True) -> list[Path]:
    """Return owned Python files with generated and cache trees excluded."""
    files: list[Path] = []
    for path in root.rglob("*.py"):
        parts = set(path.parts)
        if parts.intersection(EXCLUDED_FILE_PARTS):
            continue
        if not include_tests and ("tests" in parts or TEST_NAME_RE.match(path.name)):
            continue
        files.append(path)
    return sorted(files)


def frontend_files(root: Path, *, include_tests: bool = True) -> list[Path]:
    """Return owned frontend source files, excluding vendor and build output."""
    files: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file() or path.suffix not in SOURCE_SUFFIXES:
            continue
        parts = set(path.parts)
        if parts.intersection(EXCLUDED_FILE_PARTS):
            continue
        if not include_tests and TEST_NAME_RE.match(path.name):
            continue
        files.append(path)
    return sorted(files)


def is_owned_inventory_file(path: Path) -> bool:
    """Return whether a file belongs in high-level owned-source counts."""
    if not path.is_file() or path.name.startswith(".") or path.name in EXCLUDED_FILE_NAMES:
        return False
    if set(path.parts).intersection(EXCLUDED_FILE_PARTS):
        return False
    return path.suffix not in {".oxt", ".pyc", ".pyo"}


def parse_router_registration(
    composition_path: Path,
    app_root: Path,
) -> list[RouterRegistration]:
    """Read statically declared `app.include_router` registrations."""
    tree = ast.parse(read_text(composition_path), filename=str(composition_path))
    registrations: list[RouterRegistration] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        if expression_name(node.func) != "app.include_router" or not node.args:
            continue
        router_name = expression_name(node.args[0])
        module = router_name.removesuffix(".router")
        registrations.append(
            RouterRegistration(
                module=module,
                prefix=constant_string(keyword(node, "prefix")),
                tags=string_list(keyword(node, "tags")),
                line=node.lineno,
                source=relative_posix(composition_path, app_root),
            )
        )
    return sorted(registrations, key=lambda item: item.line)


def _python_module_path(app_root: Path, dotted_module: str) -> Path | None:
    """Resolve an owned dotted Python module without importing it."""
    candidate = app_root / f"{dotted_module.replace('.', '/')}.py"
    if candidate.is_file():
        return candidate
    package = app_root / dotted_module.replace(".", "/") / "__init__.py"
    return package if package.is_file() else None


def _import_target(path: Path, imported_name: str, app_root: Path) -> Path | None:
    """Resolve one statically imported name to an owned source module."""
    tree = ast.parse(read_text(path), filename=str(path))
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.module:
            for alias in node.names:
                local_name = alias.asname or alias.name
                if local_name != imported_name:
                    continue
                direct = _python_module_path(app_root, f"{node.module}.{alias.name}")
                return direct or _python_module_path(app_root, node.module)
        if isinstance(node, ast.Import):
            for alias in node.names:
                local_name = alias.asname or alias.name.rsplit(".", 1)[-1]
                if local_name == imported_name:
                    return _python_module_path(app_root, alias.name)
    return None


def resolve_registered_router(
    registration: RouterRegistration,
    composition_path: Path,
    app_root: Path,
) -> Path | None:
    """Follow a registered router alias through a compatibility facade."""
    path = _import_target(composition_path, registration.module, app_root)
    visited: set[Path] = set()
    while path is not None and path not in visited:
        visited.add(path)
        if declares_router(path):
            return path
        path = _import_target(path, "router", app_root)
    return None


def route_decorator_details(call: ast.Call) -> tuple[tuple[str, ...], str] | None:
    """Return methods and path from a FastAPI route decorator."""
    dotted = expression_name(call.func)
    owner, _, method = dotted.rpartition(".")
    if owner not in {"router", "app"}:
        return None
    if method not in HTTP_METHODS and method != "api_route":
        return None
    path_node = call.args[0] if call.args else keyword(call, "path")
    path = constant_string(path_node, "<dynamic-path>")
    if method == "api_route":
        methods = string_list(keyword(call, "methods")) or ("ANY",)
    else:
        methods = ("WEBSOCKET",) if method == "websocket" else (method.upper(),)
    return tuple(item.upper() for item in methods), path


def dependency_summary(function: ast.FunctionDef | ast.AsyncFunctionDef, call: ast.Call) -> str:
    """Summarize explicit FastAPI dependency guards without evaluating them."""
    guards: list[str] = []
    decorator_dependencies = keyword(call, "dependencies")
    if decorator_dependencies is not None:
        guards.append(safe_unparse(decorator_dependencies, limit=120))

    defaults = [*function.args.defaults, *function.args.kw_defaults]
    for default in defaults:
        if not isinstance(default, ast.Call):
            continue
        call_name = expression_name(default.func)
        if call_name not in {"Depends", "Security"}:
            continue
        target = safe_unparse(default.args[0] if default.args else None, limit=60)
        guards.append(f"{call_name}({target})")
    return ", ".join(dict.fromkeys(guards)) or "—"


def router_configuration(tree: ast.Module) -> RouterConfiguration:
    """Return configuration declared by the module's canonical router."""
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if not any(
            isinstance(target, ast.Name) and target.id == "router" for target in node.targets
        ):
            continue
        if not isinstance(node.value, ast.Call) or expression_name(node.value.func) != "APIRouter":
            continue
        dependency_node = keyword(node.value, "dependencies")
        return RouterConfiguration(
            prefix=constant_string(keyword(node.value, "prefix")),
            tags=string_list(keyword(node.value, "tags")),
            guard=(safe_unparse(dependency_node, limit=120) if dependency_node else ""),
        )
    return RouterConfiguration()


def _top_level_call(node: ast.stmt) -> ast.Call | None:
    """Return a call directly executed by one module-level statement."""
    if isinstance(node, ast.Expr) and isinstance(node.value, ast.Call):
        return node.value
    if isinstance(node, ast.Assign) and isinstance(node.value, ast.Call):
        return node.value
    if isinstance(node, ast.AnnAssign) and isinstance(node.value, ast.Call):
        return node.value
    return None


def _accepts_canonical_router(call: ast.Call) -> bool:
    """Return whether a composition call receives the canonical router."""
    if call.args and expression_name(call.args[0]) == "router":
        return True
    router_arg = keyword(call, "router")
    return router_arg is not None and expression_name(router_arg) == "router"


def _declares_added_router_routes(path: Path) -> bool:
    """Return whether a module registers endpoints on an injected router."""
    tree = ast.parse(read_text(path), filename=str(path))
    return any(
        isinstance(node, ast.Call) and expression_name(node.func) == "router.add_api_route"
        for node in ast.walk(tree)
    )


def imported_router_registrars(path: Path, app_root: Path) -> list[Path]:
    """Resolve imported modules that register routes on this module's router."""
    tree = ast.parse(read_text(path), filename=str(path))
    registrars: set[Path] = set()
    for node in tree.body:
        call = _top_level_call(node)
        if call is None or not _accepts_canonical_router(call):
            continue
        owner = expression_name(call.func).partition(".")[0]
        if not owner or owner in {"app", "router"}:
            continue
        target = _import_target(path, owner, app_root)
        if target is not None and _declares_added_router_routes(target):
            registrars.add(target)
    return sorted(registrars)


def parse_added_router_routes(
    path: Path,
    app_root: Path,
    registration: RouterRegistration | None,
    owner: RouterConfiguration,
) -> list[RouteOperation]:
    """Extract routes registered by a module onto an injected APIRouter."""
    tree = ast.parse(read_text(path), filename=str(path))
    functions = {
        node.name: node
        for node in ast.walk(tree)
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
    }
    operations: list[RouteOperation] = []
    for call in (node for node in ast.walk(tree) if isinstance(node, ast.Call)):
        if expression_name(call.func) != "router.add_api_route" or len(call.args) < 2:
            continue
        route_path = constant_string(call.args[0], "<dynamic-path>")
        handler_name = expression_name(call.args[1]) or "<dynamic-handler>"
        methods = string_list(keyword(call, "methods")) or ("ANY",)
        handler = functions.get(handler_name)
        dependencies = keyword(call, "dependencies")
        guards = (
            dependency_summary(handler, call)
            if handler is not None
            else safe_unparse(dependencies, limit=120)
            if dependencies
            else "—"
        )
        if owner.guard:
            guards = owner.guard if guards == "—" else f"{owner.guard}, {guards}"
        tags = tuple(
            dict.fromkeys(
                [
                    *(registration.tags if registration else ()),
                    *owner.tags,
                    *string_list(keyword(call, "tags")),
                ]
            )
        )
        for method in methods:
            operations.append(
                RouteOperation(
                    method=method.upper(),
                    path=join_url_paths(
                        registration.prefix if registration else "",
                        owner.prefix,
                        route_path,
                    ),
                    handler=handler_name,
                    module=relative_posix(path, app_root),
                    line=call.lineno,
                    tags=tags,
                    guards=guards,
                    summary=(
                        first_doc_line(handler, handler_name)
                        if handler is not None
                        else handler_name.replace("_", " ").capitalize()
                    ),
                )
            )
    return operations


def parse_route_module(
    path: Path,
    app_root: Path,
    registration: RouterRegistration | None,
) -> list[RouteOperation]:
    """Extract route operations from one Python module."""
    text = read_text(path)
    tree = ast.parse(text, filename=str(path))
    configuration = router_configuration(tree)

    operations: list[RouteOperation] = []
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            if not isinstance(decorator, ast.Call):
                continue
            details = route_decorator_details(decorator)
            if details is None:
                continue
            methods, route_path = details
            registration_prefix = registration.prefix if registration else ""
            tags = tuple(
                dict.fromkeys(
                    [
                        *(registration.tags if registration else ()),
                        *configuration.tags,
                        *string_list(keyword(decorator, "tags")),
                    ]
                )
            )
            guards = dependency_summary(node, decorator)
            if configuration.guard:
                guards = (
                    configuration.guard if guards == "—" else f"{configuration.guard}, {guards}"
                )
            source = relative_posix(path, app_root)
            for method in methods:
                operations.append(
                    RouteOperation(
                        method=method,
                        path=join_url_paths(
                            registration_prefix,
                            configuration.prefix,
                            route_path,
                        ),
                        handler=node.name,
                        module=source,
                        line=node.lineno,
                        tags=tags,
                        guards=guards,
                        summary=first_doc_line(node, node.name),
                    )
                )
    for registrar_path in imported_router_registrars(path, app_root):
        operations.extend(
            parse_added_router_routes(
                registrar_path,
                app_root,
                registration,
                configuration,
            )
        )
    return operations


def declares_router(path: Path) -> bool:
    """Return whether a Python module constructs a FastAPI `APIRouter`."""
    tree = ast.parse(read_text(path), filename=str(path))
    return any(
        isinstance(node, ast.Call) and expression_name(node.func) == "APIRouter"
        for node in ast.walk(tree)
    )


def parse_direct_app_routes(source_path: Path, app_root: Path) -> list[RouteOperation]:
    """Extract routes declared directly on the FastAPI application."""
    tree = ast.parse(read_text(source_path), filename=str(source_path))
    operations: list[RouteOperation] = []
    functions = {
        node.name: node
        for node in tree.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
    }
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            if not isinstance(decorator, ast.Call):
                continue
            details = route_decorator_details(decorator)
            if details is None or not expression_name(decorator.func).startswith("app."):
                continue
            methods, route_path = details
            for method in methods:
                operations.append(
                    RouteOperation(
                        method=method,
                        path=route_path,
                        handler=node.name,
                        module=relative_posix(source_path, app_root),
                        line=node.lineno,
                        tags=string_list(keyword(decorator, "tags")),
                        guards=dependency_summary(node, decorator),
                        summary=first_doc_line(node, node.name),
                    )
                )
    for call in (node for node in ast.walk(tree) if isinstance(node, ast.Call)):
        if expression_name(call.func) != "app.add_api_route" or len(call.args) < 2:
            continue
        route_path = constant_string(call.args[0], "<dynamic-path>")
        handler_name = expression_name(call.args[1]) or "<dynamic-handler>"
        methods = string_list(keyword(call, "methods")) or ("ANY",)
        handler = functions.get(handler_name)
        dependencies = keyword(call, "dependencies")
        guards = safe_unparse(dependencies, limit=120) if dependencies else "—"
        for method in methods:
            operations.append(
                RouteOperation(
                    method=method.upper(),
                    path=route_path,
                    handler=handler_name,
                    module=relative_posix(source_path, app_root),
                    line=call.lineno,
                    tags=string_list(keyword(call, "tags")),
                    guards=guards,
                    summary=first_doc_line(handler, handler_name)
                    if handler is not None
                    else handler_name.replace("_", " ").capitalize(),
                )
            )
    return operations


def build_api_catalog(app_root: Path) -> str:
    """Generate a source-traceable FastAPI route catalog."""
    server_path = app_root / "backend" / "server.py"
    composition_path = app_root / "backend" / "app" / "routes.py"
    if not composition_path.is_file():
        composition_path = server_path
    registrations = parse_router_registration(composition_path, app_root)
    mounted: list[tuple[RouterRegistration, Path]] = []
    for registration in registrations:
        path = resolve_registered_router(registration, composition_path, app_root)
        if path is not None:
            mounted.append((registration, path))

    discovered_paths = {
        path
        for root in (app_root / "backend" / "api", app_root / "backend" / "domains")
        for path in python_files(root, include_tests=False)
        if path.name != "__init__.py" and declares_router(path)
    }
    mounted_paths = {path for _, path in mounted}
    unregistered = sorted(discovered_paths - mounted_paths)

    operations: list[RouteOperation] = []
    for source_path in (server_path, app_root / "backend" / "app" / "factory.py"):
        if source_path.is_file():
            operations.extend(parse_direct_app_routes(source_path, app_root))
    for registration, path in mounted:
        operations.extend(parse_route_module(path, app_root, registration))
    for path in unregistered:
        operations.extend(parse_route_module(path, app_root, None))
    operations.sort(key=lambda item: (item.path, item.method, item.module, item.line))

    lines = generated_header(
        "API catalog",
        "Static inventory of FastAPI route decorators and router registrations. "
        "Use the runtime OpenAPI schema for authoritative request and response bodies.",
    )
    lines.extend(
        [
            "## Summary",
            "",
            f"- Registered routers: **{len(registrations)}**",
            f"- Discovered operations: **{len(operations)}**",
            f"- Unregistered route modules: **{len(unregistered)}**",
            "",
            "## Router registrations",
            "",
            "| Order | Router | Mount prefix | Tags | Registration |",
            "| ---: | --- | --- | --- | --- |",
        ]
    )
    for order, item in enumerate(registrations, start=1):
        lines.append(
            "| "
            + " | ".join(
                [
                    str(order),
                    f"`{item.module}.router`",
                    f"`{item.prefix or '/'}`",
                    markdown_cell(", ".join(item.tags)),
                    source_link(item.source, item.line),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Operations",
            "",
            "| Method | Effective path | Handler | Tags | Dependency guards | Summary | Source |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for item in operations:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{item.method}`",
                    f"`{markdown_cell(item.path)}`",
                    f"`{item.handler}`",
                    markdown_cell(", ".join(item.tags)),
                    markdown_cell(item.guards),
                    markdown_cell(item.summary),
                    source_link(item.module, item.line),
                ]
            )
            + " |"
        )

    lines.extend(["", "## Unregistered modules", ""])
    if unregistered:
        lines.append(
            "These files contain an `APIRouter` or route-oriented module name but are not "
            "mounted by the FastAPI composition registry. They may be obsolete, imported indirectly, or "
            "under development and require human review."
        )
        lines.append("")
        for path in unregistered:
            lines.append(f"- {source_link(relative_posix(path, app_root))}")
    else:
        lines.append("Every route module is registered.")
    lines.append("")
    return "\n".join(lines)


def python_module_metrics(path: Path) -> tuple[str, int, int, int, int, int]:
    """Return summary and structural metrics for a Python source module."""
    text = read_text(path)
    try:
        tree = ast.parse(text, filename=str(path))
    except SyntaxError:
        return "Syntax could not be parsed", len(text.splitlines()), 0, 0, 0, 0
    classes = [node for node in tree.body if isinstance(node, ast.ClassDef)]
    functions = [
        node for node in tree.body if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
    ]
    async_functions = [node for node in functions if isinstance(node, ast.AsyncFunctionDef)]
    documented = sum(bool(ast.get_docstring(node)) for node in [*classes, *functions])
    summary = first_doc_line(tree, "No module docstring")
    return (
        summary,
        len(text.splitlines()),
        len(classes),
        len(functions),
        len(async_functions),
        documented,
    )


def build_backend_catalog(app_root: Path) -> str:
    """Generate a catalog of owned backend Python modules."""
    backend_root = app_root / "backend"
    files = python_files(backend_root, include_tests=False)
    grouped: dict[str, list[Path]] = defaultdict(list)
    total_lines = 0
    for path in files:
        relative = path.relative_to(backend_root)
        group = relative.parts[0] if len(relative.parts) > 1 else "application root"
        grouped[group].append(path)

    lines = generated_header(
        "Backend module catalog",
        "Owned Python modules parsed without importing the application. Counts describe "
        "top-level declarations and are navigation aids, not complexity scores.",
    )
    lines.extend(["## Module groups", "", "| Group | Modules | Lines |", "| --- | ---: | ---: |"])
    group_metrics: dict[str, tuple[int, int]] = {}
    module_metrics: dict[Path, tuple[str, int, int, int, int, int]] = {}
    for group in sorted(grouped):
        group_lines = 0
        for path in grouped[group]:
            metrics = python_module_metrics(path)
            module_metrics[path] = metrics
            group_lines += metrics[1]
        group_metrics[group] = (len(grouped[group]), group_lines)
        total_lines += group_lines
        lines.append(f"| `{group}` | {len(grouped[group])} | {group_lines} |")
    lines.extend(
        [
            "",
            f"Total: **{len(files)} modules** and **{total_lines} source lines**.",
            "",
        ]
    )

    for group in sorted(grouped):
        lines.extend(
            [
                f"## {group}",
                "",
                "| Module | Lines | Classes | Functions | Async | Documented declarations | Purpose signal |",
                "| --- | ---: | ---: | ---: | ---: | ---: | --- |",
            ]
        )
        for path in grouped[group]:
            summary, source_lines, classes, functions, async_functions, documented = module_metrics[
                path
            ]
            source = relative_posix(path, app_root)
            lines.append(
                "| "
                + " | ".join(
                    [
                        source_link(source),
                        str(source_lines),
                        str(classes),
                        str(functions),
                        str(async_functions),
                        str(documented),
                        markdown_cell(summary),
                    ]
                )
                + " |"
            )
        lines.append("")
    return "\n".join(lines)


def boolean_keyword(call: ast.Call, name: str) -> str:
    """Render a boolean SQLAlchemy column keyword as yes, no, or source expression."""
    node = keyword(call, name)
    if isinstance(node, ast.Constant) and isinstance(node.value, bool):
        return "yes" if node.value else "no"
    return safe_unparse(node, limit=40) if node is not None else "—"


def column_foreign_key(call: ast.Call) -> str:
    """Return the first literal SQLAlchemy ForeignKey target in a column call."""
    for node in ast.walk(call):
        if (
            not isinstance(node, ast.Call)
            or expression_name(node.func).split(".")[-1] != "ForeignKey"
        ):
            continue
        if node.args:
            return constant_string(node.args[0], safe_unparse(node.args[0], limit=60))
    return "—"


def column_declaration(
    statement: ast.stmt,
) -> tuple[ast.Name, ast.Call, ast.AST | None, int] | None:
    """Return one legacy or SQLAlchemy 2 declarative column assignment."""
    target: ast.expr
    value: ast.expr | None
    annotation: ast.AST | None = None
    if isinstance(statement, ast.Assign) and len(statement.targets) == 1:
        target = statement.targets[0]
        value = statement.value
    elif isinstance(statement, ast.AnnAssign):
        target = statement.target
        value = statement.value
        annotation = statement.annotation
    else:
        return None
    if not isinstance(target, ast.Name) or not isinstance(value, ast.Call):
        return None
    if expression_name(value.func).split(".")[-1] not in {"Column", "mapped_column"}:
        return None
    return target, value, annotation, statement.lineno


def mapped_annotation_type(annotation: ast.AST | None) -> ast.AST | None:
    """Extract ``T`` from a SQLAlchemy ``Mapped[T]`` annotation."""
    if not isinstance(annotation, ast.Subscript):
        return None
    if expression_name(annotation.value).split(".")[-1] != "Mapped":
        return None
    return annotation.slice


def annotation_contains_none(annotation: ast.AST) -> bool:
    """Return whether a type expression explicitly includes ``None``."""
    if isinstance(annotation, ast.Constant):
        return annotation.value is None
    if isinstance(annotation, ast.Name):
        return annotation.id in {"None", "NoneType"}
    if isinstance(annotation, ast.BinOp) and isinstance(annotation.op, ast.BitOr):
        return annotation_contains_none(annotation.left) or annotation_contains_none(
            annotation.right
        )
    if isinstance(annotation, ast.Subscript):
        if expression_name(annotation.value).split(".")[-1] == "Optional":
            return True
        return annotation_contains_none(annotation.slice)
    if isinstance(annotation, (ast.Tuple, ast.List)):
        return any(annotation_contains_none(item) for item in annotation.elts)
    return False


def column_nullable(call: ast.Call, annotation: ast.AST | None) -> str:
    """Render explicit or SQLAlchemy-2-inferred column nullability."""
    if keyword(call, "nullable") is not None:
        return boolean_keyword(call, "nullable")
    mapped_type = mapped_annotation_type(annotation)
    if mapped_type is None:
        return "—"
    return "yes" if annotation_contains_none(mapped_type) else "no"


def build_data_model_catalog(app_root: Path) -> str:
    """Generate SQLAlchemy table and column reference without importing models."""
    model_root = app_root / "backend" / "models"
    tables: list[tuple[str, str, str, int, list[tuple[str, ...]]]] = []
    for path in sorted(model_root.glob("*.py")):
        tree = ast.parse(read_text(path), filename=str(path))
        source = relative_posix(path, app_root)
        for node in tree.body:
            if not isinstance(node, ast.ClassDef):
                continue
            table_name = ""
            for statement in node.body:
                if not isinstance(statement, ast.Assign):
                    continue
                if any(
                    isinstance(target, ast.Name) and target.id == "__tablename__"
                    for target in statement.targets
                ):
                    table_name = constant_string(statement.value)
                    break
            if not table_name:
                continue

            columns: list[tuple[str, ...]] = []
            for statement in node.body:
                declaration = column_declaration(statement)
                if declaration is None:
                    continue
                target, call, annotation, line = declaration
                type_node = call.args[0] if call.args else mapped_annotation_type(annotation)
                type_name = safe_unparse(type_node, limit=60)
                if (
                    isinstance(type_node, ast.Call)
                    and expression_name(type_node.func).split(".")[-1] == "ForeignKey"
                ):
                    type_name = "inferred"
                default_node = keyword(call, "default")
                default = (
                    "redacted"
                    if SECRET_NAME_RE.search(target.id)
                    else safe_unparse(default_node, limit=60)
                )
                columns.append(
                    (
                        target.id,
                        type_name,
                        boolean_keyword(call, "primary_key"),
                        column_nullable(call, annotation),
                        boolean_keyword(call, "unique"),
                        boolean_keyword(call, "index"),
                        column_foreign_key(call),
                        default,
                        str(line),
                    )
                )
            tables.append((table_name, node.name, source, node.lineno, columns))
    tables.sort(key=lambda item: (item[0], item[2], item[3]))

    lines = generated_header(
        "Relational data model",
        "Static SQLAlchemy table and column catalog. Runtime SQLite inspection remains "
        "authoritative for an installed instance, especially after lightweight migrations.",
    )
    lines.extend(
        [
            f"Discovered **{len(tables)} mapped tables** and "
            f"**{sum(len(item[4]) for item in tables)} mapped columns**.",
            "",
            "## Table summary",
            "",
            "| Table | Model | Columns | Source |",
            "| --- | --- | ---: | --- |",
        ]
    )
    for table_name, model_name, source, line, columns in tables:
        lines.append(
            f"| `{table_name}` | `{model_name}` | {len(columns)} | {source_link(source, line)} |"
        )

    for table_name, model_name, source, _, columns in tables:
        lines.extend(
            [
                "",
                f"## `{table_name}` — `{model_name}`",
                "",
                "| Column | Type | Primary key | Nullable | Unique | Index | Foreign key | Source default | Source |",
                "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
            ]
        )
        for (
            name,
            type_name,
            primary,
            nullable,
            unique,
            index,
            foreign_key,
            default,
            line,
        ) in columns:
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{name}`",
                        f"`{markdown_cell(type_name)}`",
                        primary,
                        nullable,
                        unique,
                        index,
                        f"`{markdown_cell(foreign_key)}`" if foreign_key != "—" else "—",
                        markdown_cell(default),
                        source_link(source, int(line)),
                    ]
                )
                + " |"
            )
    lines.append("")
    return "\n".join(lines)


def resolve_frontend_import(
    source: str, app_root: Path, *, importer: Path | None = None,
) -> str:
    """Resolve a relative import from its declaring module, without executing it."""
    if not source.startswith("."):
        return source
    source_root = (app_root / "frontend" / "src").resolve()
    base = importer.parent if importer is not None else source_root
    candidate = (base / source).resolve()
    suffixes = (".tsx", ".ts", ".jsx", ".js")
    choices = [candidate, *[candidate.with_suffix(suffix) for suffix in suffixes]]
    choices.extend(candidate / f"index{suffix}" for suffix in suffixes)
    for choice in choices:
        if (
            choice.resolve().is_relative_to(source_root)
            and choice.suffix in SOURCE_SUFFIXES
            and is_owned_inventory_file(choice)
        ):
            return relative_posix(choice, app_root)
    return source


def frontend_imports(text: str, path: Path, app_root: Path) -> dict[str, str]:
    """Resolve default, named/aliased and lazy component imports in one module."""
    imports: dict[str, str] = {}
    for clause, source in STATIC_IMPORT_RE.findall(text):
        resolved = resolve_frontend_import(source, app_root, importer=path)
        default = re.match(r"([A-Za-z_$][\w$]*)", clause)
        if default:
            imports[default.group(1)] = resolved
        named = re.search(r"\{([^}]+)\}", clause)
        if named:
            for item in named.group(1).split(","):
                binding = re.fullmatch(
                    r"([A-Za-z_$][\w$]*)(?:\s+as\s+([A-Za-z_$][\w$]*))?",
                    item.strip(),
                )
                if binding:
                    imports[binding.group(2) or binding.group(1)] = resolved
    for component, source in LAZY_IMPORT_RE.findall(text):
        imports[component] = resolve_frontend_import(source, app_root, importer=path)
    return imports


def collect_frontend_routes(
    app_root: Path, *, files: list[Path] | None = None,
) -> list[FrontendRoute]:
    """Inspect production JSX/TSX route declarations, including split routers.

    This is a static inventory, not a call graph. Keep the outer element (which
    may be a local scope/guard) and do not infer nested pages as direct mounts.
    """
    source_root = app_root / "frontend" / "src"
    files = frontend_files(source_root, include_tests=False) if files is None else files
    routes: list[FrontendRoute] = []
    for path in sorted(files):
        if {"tests", "__tests__", "fixtures", "__fixtures__"}.intersection(
            path.relative_to(source_root).parts
        ) or TEST_NAME_RE.match(path.name):
            continue
        text = read_text(path)
        declarations = ROUTE_RE.findall(text)
        if not declarations:
            continue
        imports = frontend_imports(text, path, app_root)
        if imports.get("Route") != "react-router-dom":
            continue
        local_components = set(re.findall(
            r"\b(?:function|class|const|let|var)\s+([A-Za-z_$][\w$]*)", text,
        ))
        for route_path, component in declarations:
            source = imports.get(component, "unresolved")
            if component in local_components and component not in imports:
                source = relative_posix(path, app_root)
            routes.append(FrontendRoute(route_path, component, source))
    if not routes:
        raise ValueError("No literal React Router routes found in frontend/src production source")
    return routes


def frontend_exports(text: str) -> list[str]:
    """Return conservative named/default export signals from frontend source."""
    names = set(
        re.findall(
            r"\bexport\s+(?:default\s+)?(?:async\s+)?(?:function|class|const|let|var)\s+([A-Za-z_$][\w$]*)",
            text,
        )
    )
    default_match = re.search(r"\bexport\s+default\s+([A-Za-z_$][\w$]*)", text)
    if default_match:
        names.add(default_match.group(1))
    return sorted(names)


def build_frontend_catalog(app_root: Path) -> str:
    """Generate frontend routes, modules, exports, and literal API references."""
    source_root = app_root / "frontend" / "src"
    files = frontend_files(source_root, include_tests=False)
    routes = collect_frontend_routes(app_root, files=files)

    lines = generated_header(
        "Frontend catalog",
        "Static catalog of owned React source. Literal API paths are a lower bound because "
        "many calls construct URLs dynamically.",
    )
    lines.extend(
        [
            "## Application routes",
            "",
            "| Browser path | Component | Source |",
            "| --- | --- | --- |",
        ]
    )
    for route in routes:
        source = route.source
        source_display = (
            source_link(source)
            if source != "unresolved" and source.startswith("frontend/")
            else f"`{source}`"
        )
        lines.append(f"| `{route.path}` | `{route.component}` | {source_display} |")

    grouped: dict[str, list[Path]] = defaultdict(list)
    metrics: dict[Path, tuple[int, list[str], list[str]]] = {}
    for path in files:
        relative = path.relative_to(source_root)
        group = relative.parts[0] if len(relative.parts) > 1 else "application root"
        grouped[group].append(path)
        text = read_text(path)
        metrics[path] = (
            len(text.splitlines()),
            frontend_exports(text),
            sorted(set(FRONTEND_API_RE.findall(text))),
        )

    lines.extend(
        [
            "",
            "## Source groups",
            "",
            "| Group | Files | Lines | Literal API references |",
            "| --- | ---: | ---: | ---: |",
        ]
    )
    for group in sorted(grouped):
        group_lines = sum(metrics[path][0] for path in grouped[group])
        group_apis = sum(len(metrics[path][2]) for path in grouped[group])
        lines.append(f"| `{group}` | {len(grouped[group])} | {group_lines} | {group_apis} |")

    for group in sorted(grouped):
        lines.extend(
            [
                "",
                f"## {group}",
                "",
                "| Source | Lines | Export signals | Literal API paths |",
                "| --- | ---: | --- | --- |",
            ]
        )
        for path in grouped[group]:
            source_lines, exports, api_paths = metrics[path]
            lines.append(
                "| "
                + " | ".join(
                    [
                        source_link(relative_posix(path, app_root)),
                        str(source_lines),
                        markdown_cell(", ".join(f"`{item}`" for item in exports)),
                        markdown_cell(", ".join(f"`{item}`" for item in api_paths)),
                    ]
                )
                + " |"
            )
    lines.append("")
    return "\n".join(lines)


class PythonEnvironmentVisitor(ast.NodeVisitor):
    """Collect literal environment names and safe defaults from Python AST."""

    def __init__(self, source: str, runtime: str) -> None:
        self.source = source
        self.runtime = runtime
        self.references: list[EnvironmentReference] = []

    def visit_Call(self, node: ast.Call) -> None:  # noqa: N802
        """Collect `os.getenv`, `os.environ.get`, and `setdefault` calls."""
        name = expression_name(node.func)
        supported = {
            "os.getenv",
            "os.environ.get",
            "os.environ.setdefault",
            "environ.get",
            "environ.setdefault",
        }
        if name in supported and node.args:
            env_name = constant_string(node.args[0])
            if env_name:
                default_node = node.args[1] if len(node.args) > 1 else keyword(node, "default")
                self.references.append(
                    EnvironmentReference(
                        name=env_name,
                        default=format_environment_default(env_name, default_node),
                        source=self.source,
                        line=node.lineno,
                        runtime=self.runtime,
                    )
                )
        self.generic_visit(node)

    def visit_Subscript(self, node: ast.Subscript) -> None:  # noqa: N802
        """Collect direct `os.environ[NAME]` lookups."""
        if expression_name(node.value) == "os.environ":
            env_name = constant_string(node.slice)
            if env_name:
                self.references.append(
                    EnvironmentReference(
                        name=env_name,
                        default="required",
                        source=self.source,
                        line=node.lineno,
                        runtime=self.runtime,
                    )
                )
        self.generic_visit(node)


def format_environment_default(name: str, node: ast.AST | None) -> str:
    """Render a source default while redacting secret-bearing variables."""
    if SECRET_NAME_RE.search(name):
        return "redacted"
    if node is None:
        return "unset"
    if isinstance(node, ast.Constant) and isinstance(
        node.value, (str, int, float, bool, type(None))
    ):
        value = repr(node.value)
        return value if len(value) <= 70 else f"{value[:69]}…"
    return safe_unparse(node, limit=70)


def collect_environment_references(app_root: Path) -> list[EnvironmentReference]:
    """Collect environment names from owned Python and JavaScript source."""
    references: list[EnvironmentReference] = []
    python_roots = [app_root / "backend", app_root / "pipeline", app_root / "scripts"]
    seen_python: set[Path] = set()
    for root in python_roots:
        if not root.exists():
            continue
        for path in python_files(root):
            if path in seen_python:
                continue
            seen_python.add(path)
            source = relative_posix(path, app_root)
            try:
                tree = ast.parse(read_text(path), filename=str(path))
            except SyntaxError:
                continue
            visitor = PythonEnvironmentVisitor(source, "Python")
            visitor.visit(tree)
            references.extend(visitor.references)

    javascript_roots = [app_root / "frontend" / "src", app_root / "desktop"]
    for root in javascript_roots:
        if not root.exists():
            continue
        for path in frontend_files(root):
            text = read_text(path)
            source = relative_posix(path, app_root)
            for match in FRONTEND_ENV_RE.finditer(text):
                line = text.count("\n", 0, match.start()) + 1
                references.append(
                    EnvironmentReference(
                        name=match.group(1),
                        default="runtime-provided",
                        source=source,
                        line=line,
                        runtime="Vite" if "import.meta" in match.group(0) else "Node.js",
                    )
                )
    return sorted(
        set(references),
        key=lambda item: (item.name, item.source, item.line, item.default),
    )


def build_configuration_catalog(app_root: Path) -> str:
    """Generate the environment-variable catalog without reading environment values."""
    references = collect_environment_references(app_root)
    grouped: dict[str, list[EnvironmentReference]] = defaultdict(list)
    for item in references:
        grouped[item.name].append(item)
    lines = generated_header(
        "Configuration catalog",
        "Environment names and source-written defaults discovered through static inspection. "
        "Secret-bearing defaults are always redacted, and the generator never reads the process environment.",
    )
    lines.extend(
        [
            f"Discovered **{len(grouped)} variables** across **{len(references)} source references**.",
            "",
            "| Variable | Runtime | Source default | Consumers |",
            "| --- | --- | --- | --- |",
        ]
    )
    for name in sorted(grouped):
        items = grouped[name]
        runtimes = sorted({item.runtime for item in items})
        defaults = sorted({item.default for item in items})
        consumers = "<br>".join(source_link(item.source, item.line) for item in items)
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{name}`",
                    markdown_cell(", ".join(runtimes)),
                    markdown_cell(", ".join(defaults)),
                    consumers,
                ]
            )
            + " |"
        )
    lines.append("")
    return "\n".join(lines)


def count_python_tests(path: Path) -> int:
    """Count top-level pytest test functions and class methods."""
    try:
        tree = ast.parse(read_text(path), filename=str(path))
    except SyntaxError:
        return 0
    return sum(
        isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith("test_")
        for node in ast.walk(tree)
    )


def build_test_catalog(app_root: Path) -> str:
    """Generate a test-suite inventory by runtime and source area."""
    python_tests = [
        path
        for path in python_files(app_root)
        if "tests" in path.parts or TEST_NAME_RE.match(path.name)
    ]
    frontend_tests = [
        path
        for root in [app_root / "frontend", app_root / "tests" / "e2e"]
        for path in frontend_files(root)
        if TEST_NAME_RE.match(path.name)
    ]
    rows: list[tuple[str, Path, int, str]] = []
    for path in python_tests:
        rows.append(("pytest", path, count_python_tests(path), "Python AST"))
    for path in frontend_tests:
        text = read_text(path)
        cases = len(re.findall(r"\b(?:it|test)\s*\(", text))
        runner = "Playwright" if "e2e" in path.parts else "Vitest"
        rows.append((runner, path, cases, "call-pattern estimate"))
    rows.sort(key=lambda item: (item[0], relative_posix(item[1], app_root)))

    runner_counts: dict[str, tuple[int, int]] = {}
    for runner in sorted({item[0] for item in rows}):
        selected = [item for item in rows if item[0] == runner]
        runner_counts[runner] = (len(selected), sum(item[2] for item in selected))

    lines = generated_header(
        "Test catalog",
        "Inventory of owned test files. Python test counts come from AST names; JavaScript "
        "counts are conservative call-pattern estimates and do not replace runner collection.",
    )
    lines.extend(["## Summary", "", "| Runner | Files | Test signals |", "| --- | ---: | ---: |"])
    for runner, (file_count, test_count) in runner_counts.items():
        lines.append(f"| {runner} | {file_count} | {test_count} |")
    lines.extend(
        [
            "",
            "## Files",
            "",
            "| Runner | File | Test signals | Counting method |",
            "| --- | --- | ---: | --- |",
        ]
    )
    for runner, path, cases, method in rows:
        lines.append(
            f"| {runner} | {source_link(relative_posix(path, app_root))} | {cases} | {method} |"
        )
    lines.append("")
    return "\n".join(lines)


def first_markdown_heading(text: str, fallback: str) -> str:
    """Return the first Markdown heading text."""
    for line in text.splitlines():
        if line.startswith("# "):
            return line.removeprefix("# ").strip()
    return fallback


def build_skill_catalog(app_root: Path) -> str:
    """Generate the runtime skill-package catalog."""
    skill_root = app_root / "pipeline" / "skills"
    rows: list[tuple[str, str, int, int, str]] = []
    for skill_doc in sorted(skill_root.glob("*/SKILL.md")):
        skill_dir = skill_doc.parent
        text = read_text(skill_doc)
        scripts = (
            sorted(
                path
                for path in (skill_dir / "scripts").glob("**/*")
                if path.is_file() and "__pycache__" not in path.parts
            )
            if (skill_dir / "scripts").exists()
            else []
        )
        rows.append(
            (
                skill_dir.name,
                first_markdown_heading(text, skill_dir.name),
                len(text.splitlines()),
                len(scripts),
                relative_posix(skill_doc, app_root),
            )
        )
    lines = generated_header(
        "Runtime skill catalog",
        "Packages under `pipeline/skills/` are application automation and operational "
        "capabilities. They are distinct from development-agent skills.",
    )
    lines.extend(
        [
            f"Discovered **{len(rows)} documented runtime skills**.",
            "",
            "| Skill | Declared title | Documentation lines | Scripts | Contract |",
            "| --- | --- | ---: | ---: | --- |",
        ]
    )
    for name, title, doc_lines, scripts, source in rows:
        lines.append(
            f"| `{name}` | {markdown_cell(title)} | {doc_lines} | {scripts} | {source_link(source)} |"
        )
    lines.append("")
    return "\n".join(lines)


def load_domains(config_path: Path) -> list[dict[str, object]]:
    """Load and minimally validate the curated domain coverage configuration."""
    data = json.loads(read_text(config_path))
    if not isinstance(data, list):
        raise ValueError("domains.json must contain a list")
    domains: list[dict[str, object]] = []
    for item in data:
        if not isinstance(item, dict):
            raise ValueError("Every domain entry must be an object")
        required = {"id", "name", "guide", "source_globs", "test_globs", "directives"}
        missing = required - item.keys()
        if missing:
            raise ValueError(f"Domain {item.get('id', '<unknown>')} misses {sorted(missing)}")
        domains.append(item)
    return domains


def matches_for_globs(app_root: Path, patterns: list[str]) -> list[Path]:
    """Resolve application-relative glob patterns with stable de-duplication."""
    matches: set[Path] = set()
    for pattern in patterns:
        matches.update(path for path in app_root.glob(pattern) if is_owned_inventory_file(path))
    return sorted(matches)


def build_coverage_catalog(app_root: Path, project_root: Path, domains_path: Path) -> str:
    """Generate the curated capability-to-source documentation matrix."""
    domains = load_domains(domains_path)
    lines = generated_header(
        "Documentation coverage",
        "Curated traceability matrix connecting product domains to reviewed guides, source, "
        "tests, and development-memory directives. File presence proves traceability, not behavior.",
    )
    lines.extend(
        [
            "| Domain | Status | Guide | Source files | Test files | Directives found |",
            "| --- | --- | --- | ---: | ---: | ---: |",
        ]
    )
    details: list[str] = []
    for item in domains:
        domain_id = str(item["id"])
        name = str(item["name"])
        guide = app_root / str(item["guide"])
        sources = matches_for_globs(app_root, [str(value) for value in item["source_globs"]])
        tests = matches_for_globs(app_root, [str(value) for value in item["test_globs"]])
        directive_paths = [
            project_root / "docs" / "dev_memory" / "directives" / str(value)
            for value in item["directives"]
        ]
        directives = [path for path in directive_paths if path.is_file()]
        directive_root = project_root / "docs" / "dev_memory" / "directives"
        if directive_root.is_dir() and item["directives"] and not directives:
            log.warning(
                "Domain %s declares %d directive(s) but none were found under "
                "%s/docs/dev_memory/directives — check --project-root.",
                domain_id,
                len(item["directives"]),
                project_root,
            )
        status = "covered" if guide.is_file() and sources else "gap"
        guide_source = relative_posix(guide, app_root) if guide.is_file() else str(item["guide"])
        guide_link = (
            f"[`{name}`](../{guide_source.removeprefix('docs/engineering/')})"
            if guide.is_file()
            else f"`{guide_source}`"
        )
        lines.append(
            f"| `{domain_id}` | **{status}** | {guide_link} | {len(sources)} | {len(tests)} | {len(directives)} |"
        )
        details.extend(
            [
                "",
                f"## {name}",
                "",
                f"- Guide: {guide_link}",
                f"- Source patterns: {', '.join(f'`{value}`' for value in item['source_globs'])}",
                f"- Test patterns: {', '.join(f'`{value}`' for value in item['test_globs'])}",
                "- Directives: "
                + (
                    ", ".join(f"`docs/dev_memory/directives/{path.name}`" for path in directives)
                    or "none found"
                ),
            ]
        )
    lines.extend(details)
    lines.append("")
    return "\n".join(lines)


def build_repository_inventory(app_root: Path, project_root: Path) -> str:
    """Generate high-level owned-source and documentation counts."""
    backend_all = python_files(app_root / "backend")
    backend_tests = [
        path for path in backend_all if "tests" in path.parts or TEST_NAME_RE.match(path.name)
    ]
    frontend_all = frontend_files(app_root / "frontend" / "src")
    frontend_tests = [path for path in frontend_all if TEST_NAME_RE.match(path.name)]
    route_composition = app_root / "backend" / "app" / "routes.py"
    if not route_composition.is_file():
        route_composition = app_root / "backend" / "server.py"
    route_registrations = parse_router_registration(route_composition, app_root)
    directives = sorted((project_root / "docs" / "dev_memory" / "directives").glob("*.md"))
    skills = sorted((app_root / "pipeline" / "skills").glob("*/SKILL.md"))

    owned_roots = [
        "backend",
        "frontend/src",
        "pipeline",
        "desktop",
        "extensions",
        "tests/e2e",
        "scripts",
    ]
    lines = generated_header(
        "Repository inventory",
        "High-level snapshot of the authoritative application tree. Generated and vendored "
        "dependencies are excluded where the catalog can identify them reliably.",
    )
    lines.extend(
        [
            "## Key counts",
            "",
            "| Surface | Count |",
            "| --- | ---: |",
            f"| Backend Python files | {len(backend_all)} |",
            f"| Backend Python test files | {len(backend_tests)} |",
            f"| Frontend JS/TS source files | {len(frontend_all)} |",
            f"| Frontend unit test files | {len(frontend_tests)} |",
            f"| Registered FastAPI routers | {len(route_registrations)} |",
            f"| Runtime skill contracts | {len(skills)} |",
            f"| Development-memory directives | {len(directives)} |",
            "",
            "## Owned application surfaces",
            "",
            "| Surface | Files | Purpose boundary |",
            "| --- | ---: | --- |",
        ]
    )
    purpose = {
        "backend": "FastAPI, services, models, agents, scheduling, and storage adapters",
        "frontend/src": "React application, UI behavior, state, and browser integrations",
        "pipeline": "Reusable application skills and deterministic processing tools",
        "desktop": "Desktop lifecycle, backend packaging, IPC, and updates",
        "extensions": "Office, browser, plugin, marketplace, and external-system adapters",
        "tests/e2e": "Host-level Playwright acceptance tests",
        "scripts": "Native, self-host, release, and maintenance scripts",
    }
    for source_root in owned_roots:
        root = app_root / source_root
        count = (
            sum(1 for path in root.rglob("*") if is_owned_inventory_file(path))
            if root.exists()
            else 0
        )
        lines.append(f"| `{source_root}/` | {count} | {purpose[source_root]} |")
    lines.extend(
        [
            "",
            "## Exclusion boundary",
            "",
            "Catalogs exclude or avoid interpreting `.venv`, `node_modules`, `dist`, cache "
            "directories, Playwright reports, `local_data`, local SQLite files, and "
            "`frontend/vendor`. Vendored reader code is documented only at its integration boundary.",
            "",
        ]
    )
    return "\n".join(lines)


def build_outputs(app_root: Path, project_root: Path, domains_path: Path) -> dict[str, str]:
    """Build every generated page in a stable order."""
    return {
        "api-catalog.md": build_api_catalog(app_root),
        "backend-modules.md": build_backend_catalog(app_root),
        "configuration.md": build_configuration_catalog(app_root),
        "coverage.md": build_coverage_catalog(app_root, project_root, domains_path),
        "data-model.md": build_data_model_catalog(app_root),
        "frontend-catalog.md": build_frontend_catalog(app_root),
        "repository-inventory.md": build_repository_inventory(app_root, project_root),
        "skills.md": build_skill_catalog(app_root),
        "tests.md": build_test_catalog(app_root),
    }


def write_or_check(outputs: dict[str, str], output_dir: Path, check: bool) -> int:
    """Write generated pages or report deterministic differences."""
    stale: list[str] = []
    for name, content in outputs.items():
        expected = f"{content.rstrip()}\n"
        path = output_dir / name
        if check:
            current = read_text(path) if path.is_file() else ""
            if current != expected:
                stale.append(name)
        else:
            output_dir.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
            log.info("Generated %s", path)

    existing = {path.name for path in output_dir.glob("*.md")} if output_dir.exists() else set()
    unexpected = sorted(existing - outputs.keys())
    if check and (stale or unexpected):
        if stale:
            log.error("Stale or missing generated pages: %s", ", ".join(stale))
        if unexpected:
            log.error("Unexpected generated pages: %s", ", ".join(unexpected))
        return 1
    if check:
        log.info("All %d generated pages are current", len(outputs))
    return 0


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if committed generated pages differ from current source.",
    )
    parser.add_argument(
        "--app-root",
        type=Path,
        help="Override the auto-detected Gnosi application root.",
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        help=(
            "Override the repository root that owns docs/dev_memory/directives. "
            "Defaults to auto-detection from the script location."
        ),
    )
    parser.add_argument(
        "--domains",
        type=Path,
        help="Override the curated domains JSON file.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Generate or verify the engineering reference catalogs."""
    args = parse_args(argv or sys.argv[1:])
    app_root = (args.app_root or find_app_root(Path(__file__))).resolve()
    project_root = (args.project_root or find_project_root(Path(__file__))).resolve()
    domains_path = (
        args.domains
        or app_root / "pipeline" / "skills" / "technical_documentation" / "domains.json"
    )
    if not domains_path.is_file():
        log.error("Domain configuration not found: %s", domains_path)
        return 2
    output_dir = app_root / "docs" / "engineering" / "generated"
    try:
        outputs = build_outputs(app_root, project_root, domains_path)
    except (OSError, SyntaxError, ValueError, json.JSONDecodeError) as exc:
        log.error("Documentation generation failed: %s", exc)
        return 2
    return write_or_check(outputs, output_dir, args.check)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    raise SystemExit(main())
