"""Identifiers generated by builtin profiles remain usable by chat and sessions."""
import pytest
from fastapi import HTTPException
from backend.services import builtin_plugins
from backend.domains.agent.routes.shared import _validated_identifier


def test_every_builtin_profile_uses_the_public_chat_identifier_contract():
    profiles = [entry["agent_profile"] for entry in builtin_plugins.public_registry() if entry.get("agent_profile")]
    assert profiles
    for profile in profiles:
        for label in ["profile_id", "agent_id"]:
            assert _validated_identifier(profile["id"], label) == profile["id"]


@pytest.mark.parametrize("value", ["../profile", ".hidden", "profile/name", "profile\\name", "name with spaces", "x" * 129])
def test_profile_identifiers_reject_path_and_scope_injection(value):
    with pytest.raises(HTTPException) as error:
        _validated_identifier(value, "profile_id")
    assert error.value.status_code == 422


def test_session_identifier_contract_remains_separate():
    with pytest.raises(HTTPException):
        _validated_identifier("builtin.translation.default", "session_id")
