"""GENERATED — DO NOT EDIT. Source: pipeline/skills/zotero_schema/schema.json. Regenerate with `pipeline/skills/zotero_schema/scripts/build_constants.py`."""

SCHEMA_VERSION: int = 42
SCHEMA_SOURCE_SHA: str = 'cb40cf538b7f21ad'

ALL_ITEM_TYPES: list[str] = [
    'annotation',
    'artwork',
    'attachment',
    'audioRecording',
    'bill',
    'blogPost',
    'book',
    'bookSection',
    'case',
    'computerProgram',
    'conferencePaper',
    'dataset',
    'dictionaryEntry',
    'document',
    'email',
    'encyclopediaArticle',
    'film',
    'forumPost',
    'hearing',
    'instantMessage',
    'interview',
    'journalArticle',
    'letter',
    'magazineArticle',
    'manuscript',
    'map',
    'newspaperArticle',
    'note',
    'patent',
    'podcast',
    'preprint',
    'presentation',
    'radioBroadcast',
    'report',
    'standard',
    'statute',
    'thesis',
    'tvBroadcast',
    'videoRecording',
    'webpage',
]

ZOTERO_TO_CSL_TYPE: dict[str, str] = {
    'artwork': 'graphic',
    'attachment': 'document',
    'audioRecording': 'song',
    'bill': 'bill',
    'blogPost': 'post-weblog',
    'book': 'book',
    'bookSection': 'chapter',
    'case': 'legal_case',
    'computerProgram': 'software',
    'conferencePaper': 'paper-conference',
    'dataset': 'dataset',
    'dictionaryEntry': 'entry-dictionary',
    'document': 'document',
    'email': 'personal_communication',
    'encyclopediaArticle': 'entry-encyclopedia',
    'film': 'motion_picture',
    'forumPost': 'post',
    'hearing': 'hearing',
    'instantMessage': 'personal_communication',
    'interview': 'interview',
    'journalArticle': 'article-journal',
    'letter': 'personal_communication',
    'magazineArticle': 'article-magazine',
    'manuscript': 'manuscript',
    'map': 'map',
    'newspaperArticle': 'article-newspaper',
    'note': 'document',
    'patent': 'patent',
    'podcast': 'broadcast',
    'preprint': 'article',
    'presentation': 'speech',
    'radioBroadcast': 'broadcast',
    'report': 'report',
    'standard': 'standard',
    'statute': 'legislation',
    'thesis': 'thesis',
    'tvBroadcast': 'broadcast',
    'videoRecording': 'motion_picture',
    'webpage': 'webpage',
}

ZOTERO_TYPE_LABELS: dict[str, dict[str, str]] = {
    'ca-AD': {
        'annotation': 'Anotació',
        'artwork': 'Peça artística',
        'attachment': 'Adjunció',
        'audioRecording': "Enregistrament d'àudio",
        'bill': 'Llei',
        'blogPost': 'Entrada de bloc',
        'book': 'Llibre',
        'bookSection': "Capítol d'un llibre",
        'case': 'Cas',
        'computerProgram': 'Programari',
        'conferencePaper': "Text d'una conferència",
        'dataset': 'Conjunt de dades',
        'dictionaryEntry': 'Entrada de diccionari',
        'document': 'Document',
        'email': 'Correu electrònic',
        'encyclopediaArticle': 'Article enciclopèdic',
        'film': 'Pel·lícula',
        'forumPost': 'Comentari en un fòrum',
        'hearing': 'Audició',
        'instantMessage': 'Missatge instantani',
        'interview': 'Entrevista',
        'journalArticle': 'Article de revista acadèmica',
        'letter': 'Carta',
        'magazineArticle': 'Article de revista',
        'manuscript': 'Manuscrit',
        'map': 'Mapa',
        'newspaperArticle': 'Article de premsa',
        'note': 'Nota',
        'patent': 'Patent',
        'podcast': 'Podcast',
        'preprint': 'Prepublicació',
        'presentation': 'Presentació',
        'radioBroadcast': 'Emissió de ràdio',
        'report': 'Informe',
        'standard': 'Estàndard',
        'statute': 'Estatut',
        'thesis': 'Tesi',
        'tvBroadcast': 'Emissió de televisió',
        'videoRecording': 'Enregistrament de vídeo',
        'webpage': 'Pàgina web',
    },
    'en-GB': {
        'annotation': 'Annotation',
        'artwork': 'Artwork',
        'attachment': 'Attachment',
        'audioRecording': 'Audio Recording',
        'bill': 'Bill',
        'blogPost': 'Blog Post',
        'book': 'Book',
        'bookSection': 'Book Section',
        'case': 'Case',
        'computerProgram': 'Software',
        'conferencePaper': 'Conference Paper',
        'dataset': 'Dataset',
        'dictionaryEntry': 'Dictionary Entry',
        'document': 'Document',
        'email': 'E-mail',
        'encyclopediaArticle': 'Encyclopedia Article',
        'film': 'Film',
        'forumPost': 'Forum Post',
        'hearing': 'Hearing',
        'instantMessage': 'Instant Message',
        'interview': 'Interview',
        'journalArticle': 'Journal Article',
        'letter': 'Letter',
        'magazineArticle': 'Magazine Article',
        'manuscript': 'Manuscript',
        'map': 'Map',
        'newspaperArticle': 'Newspaper Article',
        'note': 'Note',
        'patent': 'Patent',
        'podcast': 'Podcast',
        'preprint': 'Preprint',
        'presentation': 'Presentation',
        'radioBroadcast': 'Radio Broadcast',
        'report': 'Report',
        'standard': 'Standard',
        'statute': 'Statute',
        'thesis': 'Thesis',
        'tvBroadcast': 'TV Broadcast',
        'videoRecording': 'Video Recording',
        'webpage': 'Web Page',
    },
    'en-US': {
        'annotation': 'Annotation',
        'artwork': 'Artwork',
        'attachment': 'Attachment',
        'audioRecording': 'Audio Recording',
        'bill': 'Bill',
        'blogPost': 'Blog Post',
        'book': 'Book',
        'bookSection': 'Book Section',
        'case': 'Case',
        'computerProgram': 'Software',
        'conferencePaper': 'Conference Paper',
        'dataset': 'Dataset',
        'dictionaryEntry': 'Dictionary Entry',
        'document': 'Document',
        'email': 'E-mail',
        'encyclopediaArticle': 'Encyclopedia Article',
        'film': 'Film',
        'forumPost': 'Forum Post',
        'hearing': 'Hearing',
        'instantMessage': 'Instant Message',
        'interview': 'Interview',
        'journalArticle': 'Journal Article',
        'letter': 'Letter',
        'magazineArticle': 'Magazine Article',
        'manuscript': 'Manuscript',
        'map': 'Map',
        'newspaperArticle': 'Newspaper Article',
        'note': 'Note',
        'patent': 'Patent',
        'podcast': 'Podcast',
        'preprint': 'Preprint',
        'presentation': 'Presentation',
        'radioBroadcast': 'Radio Broadcast',
        'report': 'Report',
        'standard': 'Standard',
        'statute': 'Statute',
        'thesis': 'Thesis',
        'tvBroadcast': 'TV Broadcast',
        'videoRecording': 'Video Recording',
        'webpage': 'Web Page',
    },
    'es-ES': {
        'annotation': 'Anotación',
        'artwork': 'Obra de arte',
        'attachment': 'Adjunto',
        'audioRecording': 'Grabación de sonido',
        'bill': 'Propuesta de ley',
        'blogPost': 'Entrada de blog',
        'book': 'Libro',
        'bookSection': 'Sección de un libro',
        'case': 'Caso',
        'computerProgram': 'Software',
        'conferencePaper': 'Artículo en conferencia',
        'dataset': 'Conjunto de datos',
        'dictionaryEntry': 'Entrada de diccionario',
        'document': 'Documento',
        'email': 'Correo electrónico',
        'encyclopediaArticle': 'Artículo de enciclopedia',
        'film': 'Película',
        'forumPost': 'Mensaje en un foro',
        'hearing': 'Audiencia',
        'instantMessage': 'Mensaje instantáneo',
        'interview': 'Entrevista',
        'journalArticle': 'Artículo de revista académica',
        'letter': 'Carta',
        'magazineArticle': 'Artículo de revista',
        'manuscript': 'Manuscrito',
        'map': 'Mapa',
        'newspaperArticle': 'Artículo de periódico',
        'note': 'Nota',
        'patent': 'Patente',
        'podcast': 'Pódcast',
        'preprint': 'Preimpresión',
        'presentation': 'Presentación',
        'radioBroadcast': 'Emisión de radio',
        'report': 'Informe',
        'standard': 'Estándar',
        'statute': 'Estatuto',
        'thesis': 'Tesis',
        'tvBroadcast': 'Emisión de TV',
        'videoRecording': 'Grabación de vídeo',
        'webpage': 'Página web',
    },
}

LABEL_TO_ZOTERO_TYPE: dict[str, dict[str, str]] = {
    'ca-AD': {
        'Adjunció': 'attachment',
        'Anotació': 'annotation',
        'Article de premsa': 'newspaperArticle',
        'Article de revista': 'magazineArticle',
        'Article de revista acadèmica': 'journalArticle',
        'Article enciclopèdic': 'encyclopediaArticle',
        'Audició': 'hearing',
        "Capítol d'un llibre": 'bookSection',
        'Carta': 'letter',
        'Cas': 'case',
        'Comentari en un fòrum': 'forumPost',
        'Conjunt de dades': 'dataset',
        'Correu electrònic': 'email',
        'Document': 'document',
        'Emissió de ràdio': 'radioBroadcast',
        'Emissió de televisió': 'tvBroadcast',
        "Enregistrament d'àudio": 'audioRecording',
        'Enregistrament de vídeo': 'videoRecording',
        'Entrada de bloc': 'blogPost',
        'Entrada de diccionari': 'dictionaryEntry',
        'Entrevista': 'interview',
        'Estatut': 'statute',
        'Estàndard': 'standard',
        'Informe': 'report',
        'Llei': 'bill',
        'Llibre': 'book',
        'Manuscrit': 'manuscript',
        'Mapa': 'map',
        'Missatge instantani': 'instantMessage',
        'Nota': 'note',
        'Patent': 'patent',
        'Pel·lícula': 'film',
        'Peça artística': 'artwork',
        'Podcast': 'podcast',
        'Prepublicació': 'preprint',
        'Presentació': 'presentation',
        'Programari': 'computerProgram',
        'Pàgina web': 'webpage',
        'Tesi': 'thesis',
        "Text d'una conferència": 'conferencePaper',
    },
    'en-GB': {
        'Annotation': 'annotation',
        'Artwork': 'artwork',
        'Attachment': 'attachment',
        'Audio Recording': 'audioRecording',
        'Bill': 'bill',
        'Blog Post': 'blogPost',
        'Book': 'book',
        'Book Section': 'bookSection',
        'Case': 'case',
        'Conference Paper': 'conferencePaper',
        'Dataset': 'dataset',
        'Dictionary Entry': 'dictionaryEntry',
        'Document': 'document',
        'E-mail': 'email',
        'Encyclopedia Article': 'encyclopediaArticle',
        'Film': 'film',
        'Forum Post': 'forumPost',
        'Hearing': 'hearing',
        'Instant Message': 'instantMessage',
        'Interview': 'interview',
        'Journal Article': 'journalArticle',
        'Letter': 'letter',
        'Magazine Article': 'magazineArticle',
        'Manuscript': 'manuscript',
        'Map': 'map',
        'Newspaper Article': 'newspaperArticle',
        'Note': 'note',
        'Patent': 'patent',
        'Podcast': 'podcast',
        'Preprint': 'preprint',
        'Presentation': 'presentation',
        'Radio Broadcast': 'radioBroadcast',
        'Report': 'report',
        'Software': 'computerProgram',
        'Standard': 'standard',
        'Statute': 'statute',
        'TV Broadcast': 'tvBroadcast',
        'Thesis': 'thesis',
        'Video Recording': 'videoRecording',
        'Web Page': 'webpage',
    },
    'en-US': {
        'Annotation': 'annotation',
        'Artwork': 'artwork',
        'Attachment': 'attachment',
        'Audio Recording': 'audioRecording',
        'Bill': 'bill',
        'Blog Post': 'blogPost',
        'Book': 'book',
        'Book Section': 'bookSection',
        'Case': 'case',
        'Conference Paper': 'conferencePaper',
        'Dataset': 'dataset',
        'Dictionary Entry': 'dictionaryEntry',
        'Document': 'document',
        'E-mail': 'email',
        'Encyclopedia Article': 'encyclopediaArticle',
        'Film': 'film',
        'Forum Post': 'forumPost',
        'Hearing': 'hearing',
        'Instant Message': 'instantMessage',
        'Interview': 'interview',
        'Journal Article': 'journalArticle',
        'Letter': 'letter',
        'Magazine Article': 'magazineArticle',
        'Manuscript': 'manuscript',
        'Map': 'map',
        'Newspaper Article': 'newspaperArticle',
        'Note': 'note',
        'Patent': 'patent',
        'Podcast': 'podcast',
        'Preprint': 'preprint',
        'Presentation': 'presentation',
        'Radio Broadcast': 'radioBroadcast',
        'Report': 'report',
        'Software': 'computerProgram',
        'Standard': 'standard',
        'Statute': 'statute',
        'TV Broadcast': 'tvBroadcast',
        'Thesis': 'thesis',
        'Video Recording': 'videoRecording',
        'Web Page': 'webpage',
    },
    'es-ES': {
        'Adjunto': 'attachment',
        'Anotación': 'annotation',
        'Artículo de enciclopedia': 'encyclopediaArticle',
        'Artículo de periódico': 'newspaperArticle',
        'Artículo de revista': 'magazineArticle',
        'Artículo de revista académica': 'journalArticle',
        'Artículo en conferencia': 'conferencePaper',
        'Audiencia': 'hearing',
        'Carta': 'letter',
        'Caso': 'case',
        'Conjunto de datos': 'dataset',
        'Correo electrónico': 'email',
        'Documento': 'document',
        'Emisión de TV': 'tvBroadcast',
        'Emisión de radio': 'radioBroadcast',
        'Entrada de blog': 'blogPost',
        'Entrada de diccionario': 'dictionaryEntry',
        'Entrevista': 'interview',
        'Estatuto': 'statute',
        'Estándar': 'standard',
        'Grabación de sonido': 'audioRecording',
        'Grabación de vídeo': 'videoRecording',
        'Informe': 'report',
        'Libro': 'book',
        'Manuscrito': 'manuscript',
        'Mapa': 'map',
        'Mensaje en un foro': 'forumPost',
        'Mensaje instantáneo': 'instantMessage',
        'Nota': 'note',
        'Obra de arte': 'artwork',
        'Patente': 'patent',
        'Película': 'film',
        'Preimpresión': 'preprint',
        'Presentación': 'presentation',
        'Propuesta de ley': 'bill',
        'Página web': 'webpage',
        'Pódcast': 'podcast',
        'Sección de un libro': 'bookSection',
        'Software': 'computerProgram',
        'Tesis': 'thesis',
    },
}
