"""Byte-level regression fixtures for model-free generated locale parity."""

from __future__ import annotations

import os
from pathlib import Path
import re
import subprocess
import sys

import pytest

from pipeline.skills.technical_documentation.scripts import localize, pre_pr
from pipeline.skills.technical_documentation.scripts.generate import build_outputs
from pipeline.skills.technical_documentation.scripts.generated_localization import (
    PAGE_LABELS,
    localize_generated_reference,
)


SOURCE_LABEL = "`frontend/src/features/files/Source groups.ts:418`"
SOURCE_URL = (
    "https://github.com/ismigar/Gnosi/blob/main/frontend/src/features/files/"
    "Source%20groups.ts?raw=1&lang=en#L418"
)
DATA_ROW = (
    f"| [{SOURCE_LABEL}]({SOURCE_URL}) | 001 | 42 | 0 | 1 | 800 | "
    "Return `get_page_v2` from `/api/pages/{page_id}?limit=100&sort=asc`; "
    "Summary \\| Source; false; None; 3.14159; https://example.org/v1?q=%2F#L7 |\r\n"
)
FIXTURE = (
    "---\r\ntitle: Module groups\r\nsource_paths: [backend/Source.py]\r\n---\r\n"
    "<!-- Generated by pipeline/skills/technical_documentation/scripts/generate.py. "
    "Do not edit manually. -->\r\n\r\n"
    "# Backend module catalog\r\n\r\n"
    "Regenerate with `python pipeline/skills/technical_documentation/scripts/generate.py`.\r\n\r\n"
    "## Module groups\r\n\r\n"
    "| Group | Modules | Lines |\r\n| --- | ---: | ---: |\r\n"
    "| `Module groups` | 001 | 800 |\r\n\r\n"
    "## Module groups\r\n\r\n"
    "| Module | Lines | Classes | Functions | Async | Documented declarations | Purpose signal |\r\n"
    "| --- | ---: | ---: | ---: | ---: | ---: | --- |\r\n"
    + DATA_ROW
    + "\r\n````markdown\r\n```\r\n## Module groups\r\n"
    "| Group | Modules | Lines |\r\n| --- | ---: | ---: |\r\n````\r\n"
    "\r\n~~~mermaid\r\nflowchart LR\r\nA[\"Source groups\"] --> B[\"Files\"]\r\n~~~\r\n"
    "\r\nUnlisted source prose: naïve Δ; XGNOSI_IDENTIFIER."
).encode("utf-8")


def snapshot(root: Path) -> dict[str, bytes]:
    """Include configs, guides and assets when proving non-mutation."""
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in root.rglob("*") if path.is_file()
    }


@pytest.fixture
def locale_tree(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Isolate all localization IO from the actual reviewed portal."""
    source_root = tmp_path / "docs" / "engineering"
    generated = source_root / "generated"
    generated.mkdir(parents=True)
    (generated / "backend-modules.md").write_bytes(FIXTURE)
    (generated / "evidence.bin").write_bytes(b"\x00\xff\r\n001")
    (source_root / "index.md").write_bytes(b"# Reviewed English\r\n")
    (source_root / "asset.css").write_bytes(b".source { color: blue; }\r\n")
    (tmp_path / "mkdocs.yml").write_bytes(b"# Approved EN config\r\n")
    configs: dict[str, localize.LocaleConfig] = {}
    for target, original in localize.LOCALES.items():
        config = original.copy()
        config["docs_root"] = tmp_path / "docs" / f"engineering-{target}"
        config["config"] = tmp_path / f"mkdocs-{target}.yml"
        config["docs_root"].mkdir()
        (config["docs_root"] / "index.md").write_bytes(
            f"# Approved {target} guide\r\nDo not replace.\r\n".encode()
        )
        (config["docs_root"] / "asset.css").write_bytes(b"/* approved locale asset */\r\n")
        config["config"].write_bytes(f"# Approved {target} config\r\n".encode())
        configs[target] = config
    monkeypatch.setattr(localize, "SOURCE_ROOT", source_root)
    monkeypatch.setattr(localize, "APP_ROOT", tmp_path)
    monkeypatch.setattr(localize, "LOCALES", configs)
    return tmp_path


@pytest.mark.parametrize(
    ("target", "title", "groups", "header", "regenerate"),
    [
        ("ca", "Catàleg de mòduls del backend", "Grups de mòduls",
         "| Grup | Mòduls | Línies |", "Regenera amb"),
        ("es", "Catálogo de módulos del backend", "Grupos de módulos",
         "| Grupo | Módulos | Líneas |", "Regenera con"),
        ("fr", "Catalogue des modules backend", "Groupes de modules",
         "| Groupe | Modules | Lignes |", "Régénérer avec"),
    ],
)
def test_fixed_labels_change_but_technical_bytes_never_do(
    target: str, title: str, groups: str, header: str, regenerate: str,
) -> None:
    translated = localize_generated_reference(FIXTURE, target, "backend-modules.md")
    text = translated.decode()
    assert f"# {title}\r\n" in text
    assert f"## {groups}\r\n" in text
    assert header + "\r\n" in text
    assert f"{regenerate} `python pipeline/skills/technical_documentation/scripts/generate.py`." in text
    assert DATA_ROW.encode() in translated
    assert b"| `Module groups` | 001 | 800 |\r\n" in translated
    assert b"\r\n## Module groups\r\n\r\n" in translated  # Source-derived heading collision.
    assert translated.split(b"---\r\n", 2)[:2] == FIXTURE.split(b"---\r\n", 2)[:2]
    assert translated[translated.index(b"````markdown"):] == FIXTURE[FIXTURE.index(b"````markdown"):]
    assert re.findall(rb"`[^`\r\n]+`", translated) == re.findall(rb"`[^`\r\n]+`", FIXTURE)
    assert re.findall(rb"https?://[^\s)]+", translated) == re.findall(rb"https?://[^\s)]+", FIXTURE)
    assert re.findall(rb"\d+", translated) == re.findall(rb"\d+", FIXTURE)
    assert translated.count(b"\r\n") == FIXTURE.count(b"\r\n")
    assert not translated.endswith(b"\n")
    assert localize_generated_reference(translated, target, "backend-modules.md") == translated


@pytest.mark.parametrize("target", ["ca", "es", "fr"])
def test_generated_refresh_preserves_reviewed_bytes_and_is_idempotent(
    target: str, locale_tree: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    def forbidden(*args: object, **kwargs: object) -> None:
        pytest.fail("Generated-only refresh must not enter translation/configuration code")

    monkeypatch.setattr(localize, "OfflineTranslator", forbidden)
    monkeypatch.setattr(localize, "write_locale_config", forbidden)
    before = snapshot(locale_tree)
    assert localize.main(["--locale", target, "--generated-only"]) == 0
    first = snapshot(locale_tree)
    for relative, content in before.items():
        assert first[relative] == content
    expected_root = localize.LOCALES[target]["docs_root"] / "generated"
    output = expected_root / "backend-modules.md"
    assert output.read_bytes() == localize_generated_reference(FIXTURE, target, output.name)
    assert (expected_root / "evidence.bin").read_bytes() == b"\x00\xff\r\n001"
    times = {path: path.stat().st_mtime_ns for path in expected_root.iterdir()}
    assert localize.main(["--locale", target, "--generated-only"]) == 0
    assert snapshot(locale_tree) == first
    assert {path: path.stat().st_mtime_ns for path in times} == times
    assert localize.main(["--locale", target, "--check"]) == 0
    assert snapshot(locale_tree) == first


@pytest.mark.parametrize("target", ["ca", "es", "fr"])
@pytest.mark.parametrize("mutation", ["old-count", "mangled-label", "english-copy", "newline"])
def test_existing_stale_catalog_fails_read_only_check(
    target: str, mutation: str, locale_tree: Path,
) -> None:
    localize.generate_locale(target, generated_only=True)
    output = localize.LOCALES[target]["docs_root"] / "generated" / "backend-modules.md"
    valid = output.read_bytes()
    stale = {
        "old-count": valid.replace(b"| 800 |", b"| 799 |"),
        "mangled-label": valid.replace(SOURCE_LABEL.encode(), b"`translated/path.ts:418`"),
        "english-copy": FIXTURE,
        "newline": valid + b"\n",
    }[mutation]
    output.write_bytes(stale)
    before = snapshot(locale_tree)
    assert localize.check_locale(target) == ["stale generated reference generated/backend-modules.md"]
    assert localize.main(["--locale", target, "--check"]) == 1
    assert snapshot(locale_tree) == before
    localize.generate_locale(target, generated_only=True)
    assert output.read_bytes() == valid
    assert localize.check_locale(target) == []


def test_generated_only_check_does_not_require_reviewed_files_or_config(
    locale_tree: Path,
) -> None:
    # The approved files remain present for CA/ES; FR points at a new generated-only mirror.
    localize.LOCALES["fr"]["docs_root"] = locale_tree / "generated-only-fr"
    localize.LOCALES["fr"]["config"] = locale_tree / "absent.yml"
    localize.generate_locale("fr", generated_only=True)
    before = snapshot(locale_tree)
    assert localize.main(["--locale", "fr", "--generated-only", "--check"]) == 0
    assert "missing index.md" in localize.check_locale("fr")
    assert "missing absent.yml" in localize.check_locale("fr")
    assert snapshot(locale_tree) == before


def test_missing_extra_assets_and_path_selection_are_checked(locale_tree: Path) -> None:
    root = localize.LOCALES["ca"]["docs_root"] / "generated"
    selected = ["--locale", "ca", "--generated-only", "--path", "generated/backend-modules.md"]
    assert localize.main(selected) == 0
    assert localize.main(selected + ["--check"]) == 0
    assert localize.check_locale("ca", generated_only=True) == ["missing generated/evidence.bin"]
    localize.generate_locale("ca", generated_only=True)
    (root / "evidence.bin").write_bytes(b"damaged asset")
    (root / "retired.md").write_bytes(b"# Old catalog\n")
    before = snapshot(locale_tree)
    assert localize.check_locale("ca") == [
        "stale generated reference generated/evidence.bin",
        "unexpected generated reference generated/retired.md",
    ]
    assert snapshot(locale_tree) == before
    localize.generate_locale("ca", generated_only=True)
    assert (root / "retired.md").read_bytes() == b"# Old catalog\n"


@pytest.mark.parametrize("target", ["ca", "es", "fr"])
def test_every_generator_template_localizes_without_changing_its_data(
    target: str, tmp_path: Path,
) -> None:
    """Exercise actual English builders exclusively on synthetic source fixtures."""
    sources = {
        "backend/server.py": (
            "raise RuntimeError('must never import the application')\n"
            "@app.get('/api/pages/{page_id}')\n"
            "def get_page_v2():\n    '''Return Source | 42.'''\n    pass\n"
        ),
        "backend/models/page.py": (
            "class Page:\n    __tablename__ = 'pages_v2'\n"
            "    id: Mapped[int] = mapped_column(primary_key=True)\n"
            "    title: Mapped[str | None] = mapped_column(default='Source')\n"
        ),
        "frontend/src/Source groups/page.ts": (
            "export const get_page_v2 = '/api/pages/{page_id}?limit=100';\n"
        ),
        "frontend/src/App.tsx": (
            "import { Route } from 'react-router-dom';\n"
            "function Page() { return null; }\n"
            "export const App = () => <Route path='/pages/:page_id' element={<Page />} />;\n"
        ),
        "pipeline/skills/fixture/SKILL.md": "# Summary\n",
        "backend/tests/test_source.py": "def test_source():\n    pass\n",
        "domains.json": "[]",
    }
    for relative, content in sources.items():
        path = tmp_path / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    outputs = build_outputs(tmp_path, tmp_path, tmp_path / "domains.json")
    assert set(outputs) == set(PAGE_LABELS)
    for filename, english in outputs.items():
        translated = localize_generated_reference(english.encode(), target, filename).decode()
        assert translated != english
        assert f"# {PAGE_LABELS[filename][0]}\n" not in translated
        original_lines = english.splitlines()
        translated_lines = translated.splitlines()
        assert len(original_lines) == len(translated_lines)
        for index, line in enumerate(original_lines):
            if line.startswith("|") and not (
                index + 1 < len(original_lines) and original_lines[index + 1].startswith("| ---")
            ):
                assert translated_lines[index] == line
        assert re.findall(r"`[^`\n]+`", translated) == re.findall(r"`[^`\n]+`", english)


def test_unknown_catalog_and_source_domain_headings_are_opaque() -> None:
    assert localize_generated_reference(FIXTURE, "fr", "new-catalog.md") == FIXTURE
    english = b"# Documentation coverage\n\n## Files\n\n- Guide: [`Source`](../Source.md)\n"
    french = localize_generated_reference(english, "fr", "coverage.md")
    assert b"## Files\n" in french
    assert b"[`Source`](../Source.md)" in french


def test_pre_pr_refreshes_locales_after_new_english_bytes(
    locale_tree: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    for target in localize.LOCALES:
        localize.generate_locale(target, generated_only=True)
    fresh = FIXTURE.replace(b"| 800 |", b"| 801 |")

    def run_fixture_command(
        arguments: tuple[str, ...], *, cwd: Path, env: dict[str, str], check: bool,
    ) -> None:
        if arguments[1].endswith("generate.py"):
            source = localize.SOURCE_ROOT / "generated" / "backend-modules.md"
            if "--check" in arguments:
                assert source.read_bytes() == fresh
            else:
                source.write_bytes(fresh)
        else:
            assert localize.main(list(arguments[2:])) == 0

    monkeypatch.setattr(
        "pipeline.skills.technical_documentation.scripts.pre_pr.subprocess.run",
        run_fixture_command,
    )
    commands = [
        command for command in pre_pr.build_commands(base_ref=None, check_only=False)
        if command.arguments[1].endswith(("generate.py", "localize.py"))
    ]
    pre_pr.run_gate(commands)
    for target in localize.LOCALES:
        output = localize.LOCALES[target]["docs_root"] / "generated" / "backend-modules.md"
        assert output.read_bytes() == localize_generated_reference(fresh, target, output.name)


def test_generated_commands_never_import_models_or_application(locale_tree: Path) -> None:
    """A fresh process rejects imports even if the model is already cached locally."""
    script = """
import importlib.abc
from pathlib import Path
import sys
class ForbidRuntime(importlib.abc.MetaPathFinder):
    def find_spec(self, fullname, path=None, target=None):
        if fullname.split('.')[0] in {'torch', 'transformers', 'backend', 'sentencepiece',
                                      'huggingface_hub', 'fastapi', 'sqlalchemy'}:
            raise AssertionError('Forbidden runtime import: ' + fullname)
sys.meta_path.insert(0, ForbidRuntime())
from pipeline.skills.technical_documentation.scripts import localize
root = Path(sys.argv[1])
localize.APP_ROOT = root
localize.SOURCE_ROOT = root / 'docs' / 'engineering'
for target, config in localize.LOCALES.items():
    config['docs_root'] = root / 'docs' / ('engineering-' + target)
    config['config'] = root / ('mkdocs-' + target + '.yml')
assert localize.main(['--generated-only']) == 0
assert localize.main(['--check']) == 0
assert localize.main(['--generated-only']) == 0
"""
    environment = {**os.environ, "PYTHONDONTWRITEBYTECODE": "1"}
    app_root = Path(__file__).resolve().parents[4]
    subprocess.run(
        [sys.executable, "-B", "-c", script, str(locale_tree)],
        cwd=app_root, env=environment, check=True, capture_output=True, text=True,
    )
    assert localize.main(["--check"]) == 0
    # Also exercise the direct-script import branch without generating real outputs.
    subprocess.run(
        [sys.executable, "-B", str(app_root / "pipeline/skills/technical_documentation/scripts/localize.py"),
         "--help"],
        cwd=locale_tree, env=environment, check=True, capture_output=True, text=True,
    )
