"""Single typed view of the remaining citation-export facade seam."""

from __future__ import annotations

import importlib
from collections.abc import Awaitable, Callable
from contextlib import AbstractContextManager
from pathlib import Path as FilePath
from typing import Protocol, cast

from backend.domains.vault.api.pages_commands import CreateHandler
from backend.domains.vault.citations.export_contracts import (
    CitationPageEntry,
    Metadata,
    ReferenceRegistry,
    ReferenceTable,
)
from backend.domains.vault.citations.formatting import ExistingPath


class CitationExportVaultPort(Protocol):
    """Only legacy callbacks/state still lacking a canonical typed boundary.

    Callback attributes are fetched at their historical binding time; mutable
    dictionaries/locks are read from their existing owner, never copied here.
    This transitional seam does not certify the entire legacy facade.
    """

    _page_index_lock: AbstractContextManager[object]
    _page_index_entries: dict[str, dict[str, CitationPageEntry]]
    _REFERENCE_SCHEMA: list[tuple[str, str]]
    Path: Callable[[str], ExistingPath]
    create_page: CreateHandler

    def get_active_vault_path(self) -> str | FilePath | None: ...
    def _ensure_cite_key_index(self, vault_path: str) -> dict[str, Metadata]: ...
    def find_page_path(self, page_id: str) -> FilePath | None: ...
    def parse_frontmatter(self, content: str, path: FilePath) -> tuple[Metadata, str]: ...
    def get_reference_table_id(self) -> str | None: ...
    def _canonicalize_id(self, page_id: str) -> str: ...
    def _reference_table_by_id_primary(self, table_id: str) -> ReferenceTable | None: ...
    def _table_by_id(self, table_id: str) -> ReferenceTable | None: ...
    def ensure_reference_table_schema(self, table_id: str) -> int: ...
    def _set_reference_table_id(self, table_id: str | None) -> None: ...
    def _invalidate_cite_key_index(self) -> None: ...
    def create_table(self, payload: Metadata) -> Awaitable[Metadata]: ...
    def load_registry(self) -> ReferenceRegistry: ...
    def save_registry(self, registry: ReferenceRegistry) -> None: ...
    def registry_mutation(self) -> AbstractContextManager[object]: ...
    def _existing_citation_keys(self) -> set[str]: ...
    def _get_pages_snapshot(self) -> list[object]: ...
    def _is_safe_external_url(self, url: str) -> tuple[bool, str]: ...
    def _item_type_catalog_names(
        self, table: ReferenceTable | None, registry: ReferenceRegistry | None
    ) -> list[str]: ...


# This is a module boundary assertion, not a result cast or a new state owner.
# Runtime/domain contracts exercise the actual lazy callbacks through this view.
vault = cast(CitationExportVaultPort, importlib.import_module("backend.api.vault_routes"))
