"""GENERATED — DO NOT EDIT. Source: pipeline/skills/zotero_schema/schema.json. Regenerate with `pipeline/skills/zotero_schema/scripts/build_constants.py`."""

SCHEMA_VERSION: int = 42
SCHEMA_SOURCE_SHA: str = 'cb40cf538b7f21ad'

ALL_ITEM_TYPES: list[str] = [
    'annotation',
    'artwork',
    'attachment',
    'audioRecording',
    'bill',
    'blogPost',
    'book',
    'bookSection',
    'case',
    'computerProgram',
    'conferencePaper',
    'dataset',
    'dictionaryEntry',
    'document',
    'email',
    'encyclopediaArticle',
    'film',
    'forumPost',
    'hearing',
    'instantMessage',
    'interview',
    'journalArticle',
    'letter',
    'magazineArticle',
    'manuscript',
    'map',
    'newspaperArticle',
    'note',
    'patent',
    'podcast',
    'preprint',
    'presentation',
    'radioBroadcast',
    'report',
    'standard',
    'statute',
    'thesis',
    'tvBroadcast',
    'videoRecording',
    'webpage',
]

ZOTERO_TO_CSL_TYPE: dict[str, str] = {
    'artwork': 'graphic',
    'attachment': 'document',
    'audioRecording': 'song',
    'bill': 'bill',
    'blogPost': 'post-weblog',
    'book': 'book',
    'bookSection': 'chapter',
    'case': 'legal_case',
    'computerProgram': 'software',
    'conferencePaper': 'paper-conference',
    'dataset': 'dataset',
    'dictionaryEntry': 'entry-dictionary',
    'document': 'document',
    'email': 'personal_communication',
    'encyclopediaArticle': 'entry-encyclopedia',
    'film': 'motion_picture',
    'forumPost': 'post',
    'hearing': 'hearing',
    'instantMessage': 'personal_communication',
    'interview': 'interview',
    'journalArticle': 'article-journal',
    'letter': 'personal_communication',
    'magazineArticle': 'article-magazine',
    'manuscript': 'manuscript',
    'map': 'map',
    'newspaperArticle': 'article-newspaper',
    'note': 'document',
    'patent': 'patent',
    'podcast': 'broadcast',
    'preprint': 'article',
    'presentation': 'speech',
    'radioBroadcast': 'broadcast',
    'report': 'report',
    'standard': 'standard',
    'statute': 'legislation',
    'thesis': 'thesis',
    'tvBroadcast': 'broadcast',
    'videoRecording': 'motion_picture',
    'webpage': 'webpage',
}

ZOTERO_TYPE_LABELS: dict[str, dict[str, str]] = {
    'ca-AD': {
        'annotation': 'Anotació',
        'artwork': 'Peça artística',
        'attachment': 'Adjunció',
        'audioRecording': "Enregistrament d'àudio",
        'bill': 'Llei',
        'blogPost': 'Entrada de bloc',
        'book': 'Llibre',
        'bookSection': "Capítol d'un llibre",
        'case': 'Cas',
        'computerProgram': 'Programari',
        'conferencePaper': "Text d'una conferència",
        'dataset': 'Conjunt de dades',
        'dictionaryEntry': 'Entrada de diccionari',
        'document': 'Document',
        'email': 'Correu electrònic',
        'encyclopediaArticle': 'Article enciclopèdic',
        'film': 'Pel·lícula',
        'forumPost': 'Comentari en un fòrum',
        'hearing': 'Audició',
        'instantMessage': 'Missatge instantani',
        'interview': 'Entrevista',
        'journalArticle': 'Article de revista acadèmica',
        'letter': 'Carta',
        'magazineArticle': 'Article de revista',
        'manuscript': 'Manuscrit',
        'map': 'Mapa',
        'newspaperArticle': 'Article de premsa',
        'note': 'Nota',
        'patent': 'Patent',
        'podcast': 'Podcast',
        'preprint': 'Prepublicació',
        'presentation': 'Presentació',
        'radioBroadcast': 'Emissió de ràdio',
        'report': 'Informe',
        'standard': 'Estàndard',
        'statute': 'Estatut',
        'thesis': 'Tesi',
        'tvBroadcast': 'Emissió de televisió',
        'videoRecording': 'Enregistrament de vídeo',
        'webpage': 'Pàgina web',
    },
    'en-GB': {
        'annotation': 'Annotation',
        'artwork': 'Artwork',
        'attachment': 'Attachment',
        'audioRecording': 'Audio Recording',
        'bill': 'Bill',
        'blogPost': 'Blog Post',
        'book': 'Book',
        'bookSection': 'Book Section',
        'case': 'Case',
        'computerProgram': 'Software',
        'conferencePaper': 'Conference Paper',
        'dataset': 'Dataset',
        'dictionaryEntry': 'Dictionary Entry',
        'document': 'Document',
        'email': 'E-mail',
        'encyclopediaArticle': 'Encyclopedia Article',
        'film': 'Film',
        'forumPost': 'Forum Post',
        'hearing': 'Hearing',
        'instantMessage': 'Instant Message',
        'interview': 'Interview',
        'journalArticle': 'Journal Article',
        'letter': 'Letter',
        'magazineArticle': 'Magazine Article',
        'manuscript': 'Manuscript',
        'map': 'Map',
        'newspaperArticle': 'Newspaper Article',
        'note': 'Note',
        'patent': 'Patent',
        'podcast': 'Podcast',
        'preprint': 'Preprint',
        'presentation': 'Presentation',
        'radioBroadcast': 'Radio Broadcast',
        'report': 'Report',
        'standard': 'Standard',
        'statute': 'Statute',
        'thesis': 'Thesis',
        'tvBroadcast': 'TV Broadcast',
        'videoRecording': 'Video Recording',
        'webpage': 'Web Page',
    },
    'en-US': {
        'annotation': 'Annotation',
        'artwork': 'Artwork',
        'attachment': 'Attachment',
        'audioRecording': 'Audio Recording',
        'bill': 'Bill',
        'blogPost': 'Blog Post',
        'book': 'Book',
        'bookSection': 'Book Section',
        'case': 'Case',
        'computerProgram': 'Software',
        'conferencePaper': 'Conference Paper',
        'dataset': 'Dataset',
        'dictionaryEntry': 'Dictionary Entry',
        'document': 'Document',
        'email': 'E-mail',
        'encyclopediaArticle': 'Encyclopedia Article',
        'film': 'Film',
        'forumPost': 'Forum Post',
        'hearing': 'Hearing',
        'instantMessage': 'Instant Message',
        'interview': 'Interview',
        'journalArticle': 'Journal Article',
        'letter': 'Letter',
        'magazineArticle': 'Magazine Article',
        'manuscript': 'Manuscript',
        'map': 'Map',
        'newspaperArticle': 'Newspaper Article',
        'note': 'Note',
        'patent': 'Patent',
        'podcast': 'Podcast',
        'preprint': 'Preprint',
        'presentation': 'Presentation',
        'radioBroadcast': 'Radio Broadcast',
        'report': 'Report',
        'standard': 'Standard',
        'statute': 'Statute',
        'thesis': 'Thesis',
        'tvBroadcast': 'TV Broadcast',
        'videoRecording': 'Video Recording',
        'webpage': 'Web Page',
    },
    'es-ES': {
        'annotation': 'Anotación',
        'artwork': 'Obra de arte',
        'attachment': 'Adjunto',
        'audioRecording': 'Grabación de sonido',
        'bill': 'Propuesta de ley',
        'blogPost': 'Entrada de blog',
        'book': 'Libro',
        'bookSection': 'Sección de un libro',
        'case': 'Caso',
        'computerProgram': 'Software',
        'conferencePaper': 'Artículo en conferencia',
        'dataset': 'Conjunto de datos',
        'dictionaryEntry': 'Entrada de diccionario',
        'document': 'Documento',
        'email': 'Correo electrónico',
        'encyclopediaArticle': 'Artículo de enciclopedia',
        'film': 'Película',
        'forumPost': 'Mensaje en un foro',
        'hearing': 'Audiencia',
        'instantMessage': 'Mensaje instantáneo',
        'interview': 'Entrevista',
        'journalArticle': 'Artículo de revista académica',
        'letter': 'Carta',
        'magazineArticle': 'Artículo de revista',
        'manuscript': 'Manuscrito',
        'map': 'Mapa',
        'newspaperArticle': 'Artículo de periódico',
        'note': 'Nota',
        'patent': 'Patente',
        'podcast': 'Pódcast',
        'preprint': 'Preimpresión',
        'presentation': 'Presentación',
        'radioBroadcast': 'Emisión de radio',
        'report': 'Informe',
        'standard': 'Estándar',
        'statute': 'Estatuto',
        'thesis': 'Tesis',
        'tvBroadcast': 'Emisión de TV',
        'videoRecording': 'Grabación de vídeo',
        'webpage': 'Página web',
    },
    'fr-FR': {
        'annotation': 'Annotation',
        'artwork': 'Illustration',
        'attachment': 'Pièce jointe',
        'audioRecording': 'Enregistrement audio',
        'bill': 'Projet/proposition de loi',
        'blogPost': 'Billet de blog',
        'book': 'Livre',
        'bookSection': 'Chapitre de livre',
        'case': 'Affaire',
        'computerProgram': 'Logiciel',
        'conferencePaper': 'Article de colloque',
        'dataset': 'Jeu de données',
        'dictionaryEntry': 'Entrée de dictionnaire',
        'document': 'Document',
        'email': 'Courriel',
        'encyclopediaArticle': "Article d'encyclopédie",
        'film': 'Film',
        'forumPost': 'Message de forum',
        'hearing': 'Audience',
        'instantMessage': 'Message instantané',
        'interview': 'Interview',
        'journalArticle': 'Article de revue',
        'letter': 'Lettre',
        'magazineArticle': 'Article de magazine',
        'manuscript': 'Manuscrit',
        'map': 'Carte',
        'newspaperArticle': 'Article de journal',
        'note': 'Note',
        'patent': 'Brevet',
        'podcast': 'Balado (Podcast)',
        'preprint': 'Prépublication',
        'presentation': 'Présentation',
        'radioBroadcast': 'Émission de radio',
        'report': 'Rapport',
        'standard': 'Norme',
        'statute': 'Acte juridique',
        'thesis': 'Thèse',
        'tvBroadcast': 'Émission de TV',
        'videoRecording': 'Enregistrement vidéo',
        'webpage': 'Page Web',
    },
}

LABEL_TO_ZOTERO_TYPE: dict[str, dict[str, str]] = {
    'ca-AD': {
        'Adjunció': 'attachment',
        'Anotació': 'annotation',
        'Article de premsa': 'newspaperArticle',
        'Article de revista': 'magazineArticle',
        'Article de revista acadèmica': 'journalArticle',
        'Article enciclopèdic': 'encyclopediaArticle',
        'Audició': 'hearing',
        "Capítol d'un llibre": 'bookSection',
        'Carta': 'letter',
        'Cas': 'case',
        'Comentari en un fòrum': 'forumPost',
        'Conjunt de dades': 'dataset',
        'Correu electrònic': 'email',
        'Document': 'document',
        'Emissió de ràdio': 'radioBroadcast',
        'Emissió de televisió': 'tvBroadcast',
        "Enregistrament d'àudio": 'audioRecording',
        'Enregistrament de vídeo': 'videoRecording',
        'Entrada de bloc': 'blogPost',
        'Entrada de diccionari': 'dictionaryEntry',
        'Entrevista': 'interview',
        'Estatut': 'statute',
        'Estàndard': 'standard',
        'Informe': 'report',
        'Llei': 'bill',
        'Llibre': 'book',
        'Manuscrit': 'manuscript',
        'Mapa': 'map',
        'Missatge instantani': 'instantMessage',
        'Nota': 'note',
        'Patent': 'patent',
        'Pel·lícula': 'film',
        'Peça artística': 'artwork',
        'Podcast': 'podcast',
        'Prepublicació': 'preprint',
        'Presentació': 'presentation',
        'Programari': 'computerProgram',
        'Pàgina web': 'webpage',
        'Tesi': 'thesis',
        "Text d'una conferència": 'conferencePaper',
    },
    'en-GB': {
        'Annotation': 'annotation',
        'Artwork': 'artwork',
        'Attachment': 'attachment',
        'Audio Recording': 'audioRecording',
        'Bill': 'bill',
        'Blog Post': 'blogPost',
        'Book': 'book',
        'Book Section': 'bookSection',
        'Case': 'case',
        'Conference Paper': 'conferencePaper',
        'Dataset': 'dataset',
        'Dictionary Entry': 'dictionaryEntry',
        'Document': 'document',
        'E-mail': 'email',
        'Encyclopedia Article': 'encyclopediaArticle',
        'Film': 'film',
        'Forum Post': 'forumPost',
        'Hearing': 'hearing',
        'Instant Message': 'instantMessage',
        'Interview': 'interview',
        'Journal Article': 'journalArticle',
        'Letter': 'letter',
        'Magazine Article': 'magazineArticle',
        'Manuscript': 'manuscript',
        'Map': 'map',
        'Newspaper Article': 'newspaperArticle',
        'Note': 'note',
        'Patent': 'patent',
        'Podcast': 'podcast',
        'Preprint': 'preprint',
        'Presentation': 'presentation',
        'Radio Broadcast': 'radioBroadcast',
        'Report': 'report',
        'Software': 'computerProgram',
        'Standard': 'standard',
        'Statute': 'statute',
        'TV Broadcast': 'tvBroadcast',
        'Thesis': 'thesis',
        'Video Recording': 'videoRecording',
        'Web Page': 'webpage',
    },
    'en-US': {
        'Annotation': 'annotation',
        'Artwork': 'artwork',
        'Attachment': 'attachment',
        'Audio Recording': 'audioRecording',
        'Bill': 'bill',
        'Blog Post': 'blogPost',
        'Book': 'book',
        'Book Section': 'bookSection',
        'Case': 'case',
        'Conference Paper': 'conferencePaper',
        'Dataset': 'dataset',
        'Dictionary Entry': 'dictionaryEntry',
        'Document': 'document',
        'E-mail': 'email',
        'Encyclopedia Article': 'encyclopediaArticle',
        'Film': 'film',
        'Forum Post': 'forumPost',
        'Hearing': 'hearing',
        'Instant Message': 'instantMessage',
        'Interview': 'interview',
        'Journal Article': 'journalArticle',
        'Letter': 'letter',
        'Magazine Article': 'magazineArticle',
        'Manuscript': 'manuscript',
        'Map': 'map',
        'Newspaper Article': 'newspaperArticle',
        'Note': 'note',
        'Patent': 'patent',
        'Podcast': 'podcast',
        'Preprint': 'preprint',
        'Presentation': 'presentation',
        'Radio Broadcast': 'radioBroadcast',
        'Report': 'report',
        'Software': 'computerProgram',
        'Standard': 'standard',
        'Statute': 'statute',
        'TV Broadcast': 'tvBroadcast',
        'Thesis': 'thesis',
        'Video Recording': 'videoRecording',
        'Web Page': 'webpage',
    },
    'es-ES': {
        'Adjunto': 'attachment',
        'Anotación': 'annotation',
        'Artículo de enciclopedia': 'encyclopediaArticle',
        'Artículo de periódico': 'newspaperArticle',
        'Artículo de revista': 'magazineArticle',
        'Artículo de revista académica': 'journalArticle',
        'Artículo en conferencia': 'conferencePaper',
        'Audiencia': 'hearing',
        'Carta': 'letter',
        'Caso': 'case',
        'Conjunto de datos': 'dataset',
        'Correo electrónico': 'email',
        'Documento': 'document',
        'Emisión de TV': 'tvBroadcast',
        'Emisión de radio': 'radioBroadcast',
        'Entrada de blog': 'blogPost',
        'Entrada de diccionario': 'dictionaryEntry',
        'Entrevista': 'interview',
        'Estatuto': 'statute',
        'Estándar': 'standard',
        'Grabación de sonido': 'audioRecording',
        'Grabación de vídeo': 'videoRecording',
        'Informe': 'report',
        'Libro': 'book',
        'Manuscrito': 'manuscript',
        'Mapa': 'map',
        'Mensaje en un foro': 'forumPost',
        'Mensaje instantáneo': 'instantMessage',
        'Nota': 'note',
        'Obra de arte': 'artwork',
        'Patente': 'patent',
        'Película': 'film',
        'Preimpresión': 'preprint',
        'Presentación': 'presentation',
        'Propuesta de ley': 'bill',
        'Página web': 'webpage',
        'Pódcast': 'podcast',
        'Sección de un libro': 'bookSection',
        'Software': 'computerProgram',
        'Tesis': 'thesis',
    },
    'fr-FR': {
        'Acte juridique': 'statute',
        'Affaire': 'case',
        'Annotation': 'annotation',
        "Article d'encyclopédie": 'encyclopediaArticle',
        'Article de colloque': 'conferencePaper',
        'Article de journal': 'newspaperArticle',
        'Article de magazine': 'magazineArticle',
        'Article de revue': 'journalArticle',
        'Audience': 'hearing',
        'Balado (Podcast)': 'podcast',
        'Billet de blog': 'blogPost',
        'Brevet': 'patent',
        'Carte': 'map',
        'Chapitre de livre': 'bookSection',
        'Courriel': 'email',
        'Document': 'document',
        'Enregistrement audio': 'audioRecording',
        'Enregistrement vidéo': 'videoRecording',
        'Entrée de dictionnaire': 'dictionaryEntry',
        'Film': 'film',
        'Illustration': 'artwork',
        'Interview': 'interview',
        'Jeu de données': 'dataset',
        'Lettre': 'letter',
        'Livre': 'book',
        'Logiciel': 'computerProgram',
        'Manuscrit': 'manuscript',
        'Message de forum': 'forumPost',
        'Message instantané': 'instantMessage',
        'Norme': 'standard',
        'Note': 'note',
        'Page Web': 'webpage',
        'Pièce jointe': 'attachment',
        'Projet/proposition de loi': 'bill',
        'Prépublication': 'preprint',
        'Présentation': 'presentation',
        'Rapport': 'report',
        'Thèse': 'thesis',
        'Émission de TV': 'tvBroadcast',
        'Émission de radio': 'radioBroadcast',
    },
}

ITEM_TYPE_FIELDS: dict[str, list[str]] = {
    'annotation': [],
    'artwork': ['title', 'abstractNote', 'artworkMedium', 'artworkSize', 'date', 'eventPlace', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'attachment': ['title', 'accessDate', 'url'],
    'audioRecording': ['title', 'abstractNote', 'audioRecordingFormat', 'seriesTitle', 'volume', 'numberOfVolumes', 'label', 'place', 'date', 'runningTime', 'ISBN', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'bill': ['title', 'abstractNote', 'billNumber', 'code', 'codeVolume', 'section', 'codePages', 'legislativeBody', 'session', 'history', 'date', 'DOI', 'citationKey', 'url', 'accessDate', 'shortTitle', 'language', 'rights', 'extra'],
    'blogPost': ['title', 'abstractNote', 'blogTitle', 'websiteType', 'date', 'DOI', 'citationKey', 'url', 'accessDate', 'ISSN', 'shortTitle', 'language', 'rights', 'extra'],
    'book': ['title', 'abstractNote', 'series', 'seriesNumber', 'volume', 'numberOfVolumes', 'edition', 'date', 'publisher', 'place', 'originalDate', 'originalPublisher', 'originalPlace', 'format', 'numPages', 'ISBN', 'DOI', 'citationKey', 'url', 'accessDate', 'ISSN', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'bookSection': ['title', 'abstractNote', 'bookTitle', 'series', 'seriesNumber', 'volume', 'numberOfVolumes', 'edition', 'date', 'publisher', 'place', 'originalDate', 'originalPublisher', 'originalPlace', 'format', 'pages', 'ISBN', 'DOI', 'citationKey', 'url', 'accessDate', 'ISSN', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'case': ['caseName', 'abstractNote', 'court', 'dateDecided', 'docketNumber', 'reporter', 'reporterVolume', 'firstPage', 'history', 'DOI', 'citationKey', 'url', 'accessDate', 'shortTitle', 'language', 'rights', 'extra'],
    'computerProgram': ['title', 'abstractNote', 'seriesTitle', 'versionNumber', 'date', 'system', 'company', 'place', 'programmingLanguage', 'rights', 'citationKey', 'url', 'accessDate', 'DOI', 'ISBN', 'archive', 'archiveLocation', 'libraryCatalog', 'callNumber', 'shortTitle', 'extra'],
    'conferencePaper': ['title', 'abstractNote', 'proceedingsTitle', 'conferenceName', 'publisher', 'place', 'date', 'eventPlace', 'volume', 'issue', 'numberOfVolumes', 'pages', 'series', 'seriesNumber', 'DOI', 'ISBN', 'citationKey', 'url', 'accessDate', 'ISSN', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'dataset': ['title', 'abstractNote', 'identifier', 'type', 'versionNumber', 'date', 'repository', 'repositoryLocation', 'format', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'dictionaryEntry': ['title', 'abstractNote', 'dictionaryTitle', 'series', 'seriesNumber', 'volume', 'numberOfVolumes', 'edition', 'date', 'publisher', 'place', 'pages', 'ISBN', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'document': ['title', 'abstractNote', 'type', 'date', 'publisher', 'place', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'email': ['subject', 'abstractNote', 'date', 'DOI', 'citationKey', 'url', 'accessDate', 'shortTitle', 'language', 'rights', 'extra'],
    'encyclopediaArticle': ['title', 'abstractNote', 'encyclopediaTitle', 'series', 'seriesNumber', 'volume', 'numberOfVolumes', 'edition', 'date', 'publisher', 'place', 'pages', 'ISBN', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'film': ['title', 'abstractNote', 'distributor', 'place', 'date', 'genre', 'videoRecordingFormat', 'runningTime', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'forumPost': ['title', 'abstractNote', 'forumTitle', 'postType', 'date', 'DOI', 'citationKey', 'url', 'accessDate', 'shortTitle', 'language', 'rights', 'extra'],
    'hearing': ['title', 'abstractNote', 'committee', 'publisher', 'numberOfVolumes', 'documentNumber', 'pages', 'legislativeBody', 'session', 'history', 'date', 'place', 'DOI', 'citationKey', 'url', 'accessDate', 'shortTitle', 'language', 'rights', 'extra'],
    'instantMessage': ['title', 'abstractNote', 'date', 'DOI', 'citationKey', 'url', 'accessDate', 'shortTitle', 'language', 'rights', 'extra'],
    'interview': ['title', 'abstractNote', 'interviewMedium', 'date', 'publisher', 'place', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'journalArticle': ['title', 'abstractNote', 'publicationTitle', 'publisher', 'place', 'date', 'volume', 'issue', 'section', 'partNumber', 'partTitle', 'pages', 'series', 'seriesTitle', 'seriesText', 'journalAbbreviation', 'DOI', 'citationKey', 'url', 'accessDate', 'PMID', 'PMCID', 'ISSN', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'letter': ['title', 'abstractNote', 'letterType', 'date', 'eventPlace', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'magazineArticle': ['title', 'abstractNote', 'publicationTitle', 'publisher', 'place', 'date', 'volume', 'issue', 'pages', 'ISSN', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'manuscript': ['title', 'abstractNote', 'manuscriptType', 'institution', 'place', 'date', 'numPages', 'number', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'map': ['title', 'abstractNote', 'mapType', 'scale', 'seriesTitle', 'edition', 'publisher', 'place', 'date', 'DOI', 'ISBN', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'newspaperArticle': ['title', 'abstractNote', 'publicationTitle', 'publisher', 'place', 'date', 'volume', 'issue', 'edition', 'section', 'pages', 'ISSN', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'note': [],
    'patent': ['title', 'abstractNote', 'place', 'country', 'assignee', 'issuingAuthority', 'patentNumber', 'filingDate', 'pages', 'applicationNumber', 'priorityNumbers', 'issueDate', 'priorityDate', 'references', 'legalStatus', 'DOI', 'citationKey', 'url', 'accessDate', 'shortTitle', 'language', 'rights', 'extra'],
    'podcast': ['title', 'abstractNote', 'seriesTitle', 'episodeNumber', 'audioFileType', 'date', 'publisher', 'place', 'runningTime', 'DOI', 'citationKey', 'url', 'accessDate', 'shortTitle', 'language', 'rights', 'extra'],
    'preprint': ['title', 'abstractNote', 'genre', 'repository', 'archiveID', 'place', 'date', 'series', 'seriesNumber', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'presentation': ['title', 'abstractNote', 'presentationType', 'date', 'meetingName', 'place', 'series', 'sessionTitle', 'DOI', 'citationKey', 'url', 'accessDate', 'shortTitle', 'language', 'rights', 'extra'],
    'radioBroadcast': ['title', 'abstractNote', 'programTitle', 'episodeNumber', 'audioRecordingFormat', 'network', 'place', 'date', 'runningTime', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'report': ['title', 'abstractNote', 'reportNumber', 'reportType', 'institution', 'place', 'date', 'seriesTitle', 'seriesNumber', 'pages', 'DOI', 'ISBN', 'citationKey', 'url', 'accessDate', 'ISSN', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'standard': ['title', 'abstractNote', 'organization', 'committee', 'type', 'number', 'versionNumber', 'edition', 'status', 'date', 'publisher', 'place', 'partNumber', 'partTitle', 'ISBN', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'numPages', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'statute': ['nameOfAct', 'abstractNote', 'code', 'codeNumber', 'publicLawNumber', 'dateEnacted', 'pages', 'section', 'session', 'history', 'DOI', 'citationKey', 'url', 'accessDate', 'shortTitle', 'language', 'rights', 'extra'],
    'thesis': ['title', 'abstractNote', 'thesisType', 'university', 'place', 'date', 'series', 'seriesNumber', 'numPages', 'DOI', 'ISBN', 'citationKey', 'url', 'accessDate', 'ISSN', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'tvBroadcast': ['title', 'abstractNote', 'programTitle', 'episodeNumber', 'videoRecordingFormat', 'network', 'place', 'date', 'runningTime', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'videoRecording': ['title', 'abstractNote', 'videoRecordingFormat', 'seriesTitle', 'volume', 'numberOfVolumes', 'studio', 'place', 'date', 'runningTime', 'ISBN', 'DOI', 'citationKey', 'url', 'accessDate', 'archive', 'archiveLocation', 'shortTitle', 'language', 'libraryCatalog', 'callNumber', 'rights', 'extra'],
    'webpage': ['title', 'abstractNote', 'websiteTitle', 'websiteType', 'date', 'publisher', 'place', 'DOI', 'citationKey', 'url', 'accessDate', 'shortTitle', 'language', 'rights', 'extra'],
}
