"""Typed option catalogs, semantic roles and status seeds."""

from backend.domains.vault.tables.catalogs.core import (
    OPTION_COLOR_PALETTE,
    OPTION_TYPES,
    auto_color,
    get_prop_config,
    get_prop_options,
    is_global_status_prop,
    normalize_option,
    normalize_options,
    option_names,
    set_prop_options,
)
from backend.domains.vault.tables.catalogs.global_status import (
    ensure_global_status_catalog,
)
from backend.domains.vault.tables.catalogs.roles import (
    ROLE_LANGUAGE,
    ROLE_STATUS,
    ROLE_TAGS,
    assign_roles,
    find_role_prop,
    prop_role,
    table_has_social_column,
)
from backend.domains.vault.tables.catalogs.seeds import (
    BASE_STATUS_SEED,
    DEFAULT_STATUS_GROUPS,
    STATUS_CATALOG_REF,
    STATUS_DRAFT,
    STATUS_PUBLISHED_DRUPAL,
    STATUS_PUBLISHED_SOCIAL,
    STATUS_REVIEWED,
    STATUS_TRANSLATED,
    ensure_options_exist,
    ensure_status_seed,
    ensure_table_seeds,
    normalize_table_options,
)

__all__ = [
    "BASE_STATUS_SEED",
    "DEFAULT_STATUS_GROUPS",
    "OPTION_COLOR_PALETTE",
    "OPTION_TYPES",
    "ROLE_LANGUAGE",
    "ROLE_STATUS",
    "ROLE_TAGS",
    "STATUS_CATALOG_REF",
    "STATUS_DRAFT",
    "STATUS_PUBLISHED_DRUPAL",
    "STATUS_PUBLISHED_SOCIAL",
    "STATUS_REVIEWED",
    "STATUS_TRANSLATED",
    "assign_roles",
    "auto_color",
    "ensure_global_status_catalog",
    "ensure_options_exist",
    "ensure_status_seed",
    "ensure_table_seeds",
    "find_role_prop",
    "get_prop_config",
    "get_prop_options",
    "is_global_status_prop",
    "normalize_option",
    "normalize_options",
    "normalize_table_options",
    "option_names",
    "prop_role",
    "set_prop_options",
    "table_has_social_column",
]
