#!/usr/bin/env python3
"""Validate reviewed and generated Gnosi engineering documentation."""

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import unquote


log = logging.getLogger(__name__)

GENERATED_NOTICE = (
    "<!-- Generated by pipeline/skills/technical_documentation/scripts/generate.py. "
    "Do not edit manually. -->"
)
ALLOWED_STATUSES = {"implemented", "partial", "experimental", "planned", "deprecated"}
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
MARKDOWN_LINK_RE = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
NAV_PAGE_RE = re.compile(r":\s*([^\s#]+\.md)\s*$")
LOCAL_PATH_RE = re.compile(r"/(?:Users|home)/[A-Za-z0-9._-]+/")
PRIVATE_KEY_RE = re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")
API_SECRET_RE = re.compile(r"\b(?:sk|ghp|xox[baprs])-[A-Za-z0-9_-]{16,}\b")


@dataclass(frozen=True)
class PageMetadata:
    """Parsed subset of engineering-page YAML front matter."""

    status: str
    last_verified: str
    source_paths: tuple[str, ...]
    tests: tuple[str, ...]


def find_app_root(start: Path) -> Path:
    """Return the application root containing the backend and frontend trees."""
    for candidate in (start.resolve(), *start.resolve().parents):
        if (candidate / "backend").is_dir() and (candidate / "frontend").is_dir():
            return candidate
    raise RuntimeError(f"Could not locate the Gnosi application root from {start}")


def read_text(path: Path) -> str:
    """Read a UTF-8 documentation or configuration file."""
    return path.read_text(encoding="utf-8", errors="replace")


def parse_metadata(path: Path) -> PageMetadata:
    """Parse the small front-matter subset required by the portal."""
    lines = read_text(path).splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError("missing opening YAML front matter")
    try:
        closing = lines.index("---", 1)
    except ValueError as exc:
        raise ValueError("missing closing YAML front matter") from exc

    scalars: dict[str, str] = {}
    lists: dict[str, list[str]] = {"source_paths": [], "tests": []}
    active_list = ""
    for raw_line in lines[1:closing]:
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("- ") and active_list:
            lists[active_list].append(stripped[2:].strip().strip("'\""))
            continue
        active_list = ""
        if ":" not in stripped:
            continue
        key, value = (part.strip() for part in stripped.split(":", 1))
        if key in lists:
            active_list = key
            if value == "[]":
                lists[key] = []
        else:
            scalars[key] = value.strip("'\"")

    return PageMetadata(
        status=scalars.get("status", ""),
        last_verified=scalars.get("last_verified", ""),
        source_paths=tuple(lists["source_paths"]),
        tests=tuple(lists["tests"]),
    )


def validate_metadata(path: Path, app_root: Path) -> list[str]:
    """Validate status, date, and traceability paths for one reviewed page."""
    errors: list[str] = []
    try:
        metadata = parse_metadata(path)
    except ValueError as exc:
        return [f"{path}: {exc}"]
    if metadata.status not in ALLOWED_STATUSES:
        errors.append(f"{path}: invalid or missing status `{metadata.status}`")
    if not DATE_RE.match(metadata.last_verified):
        errors.append(f"{path}: invalid or missing last_verified date")
    if not metadata.source_paths:
        errors.append(f"{path}: source_paths must contain at least one traceability target")
    for category, entries in (
        ("source_paths", metadata.source_paths),
        ("tests", metadata.tests),
    ):
        for entry in entries:
            candidate = (app_root / entry).resolve()
            try:
                candidate.relative_to(app_root.resolve())
            except ValueError:
                errors.append(f"{path}: {category} target escapes the application root: {entry}")
                continue
            if not candidate.exists():
                errors.append(f"{path}: missing {category} target: {entry}")
    return errors


def clean_link_target(raw_target: str) -> str:
    """Remove optional Markdown title and angle brackets from a link target."""
    target = raw_target.strip()
    if target.startswith("<") and ">" in target:
        return target[1 : target.index(">")]
    if " \"" in target:
        target = target.split(" \"", 1)[0]
    if " '" in target:
        target = target.split(" '", 1)[0]
    return target


def validate_internal_links(path: Path, docs_root: Path) -> list[str]:
    """Validate internal Markdown link targets for one page."""
    errors: list[str] = []
    text = read_text(path)
    for raw_target in MARKDOWN_LINK_RE.findall(text):
        target = clean_link_target(raw_target)
        if not target or target.startswith(("#", "http://", "https://", "mailto:")):
            continue
        target_path = unquote(target.split("#", 1)[0].split("?", 1)[0])
        if not target_path:
            continue
        candidate = (docs_root / target_path.lstrip("/")) if target_path.startswith("/") else (path.parent / target_path)
        if not candidate.resolve().exists():
            errors.append(f"{path}: broken internal link `{target}`")
    return errors


def validate_navigation(mkdocs_path: Path, docs_root: Path) -> list[str]:
    """Validate every Markdown page named in MkDocs navigation."""
    errors: list[str] = []
    for line_number, line in enumerate(read_text(mkdocs_path).splitlines(), start=1):
        match = NAV_PAGE_RE.search(line)
        if not match:
            continue
        target = docs_root / match.group(1)
        if not target.is_file():
            errors.append(
                f"{mkdocs_path}:{line_number}: navigation target does not exist: {match.group(1)}"
            )
    return errors


def validate_domains(domains_path: Path, app_root: Path) -> list[str]:
    """Validate curated domain guides and source patterns."""
    errors: list[str] = []
    try:
        domains = json.loads(read_text(domains_path))
    except (OSError, json.JSONDecodeError) as exc:
        return [f"{domains_path}: cannot load domain configuration: {exc}"]
    if not isinstance(domains, list):
        return [f"{domains_path}: top-level value must be a list"]
    identifiers: set[str] = set()
    for item in domains:
        if not isinstance(item, dict):
            errors.append(f"{domains_path}: domain entry is not an object")
            continue
        domain_id = str(item.get("id", ""))
        if not domain_id:
            errors.append(f"{domains_path}: domain entry has no id")
        elif domain_id in identifiers:
            errors.append(f"{domains_path}: duplicate domain id `{domain_id}`")
        identifiers.add(domain_id)
        guide = app_root / str(item.get("guide", ""))
        if not guide.is_file():
            errors.append(f"{domains_path}: {domain_id} guide does not exist: {guide}")
        source_patterns = item.get("source_globs", [])
        if not isinstance(source_patterns, list) or not source_patterns:
            errors.append(f"{domains_path}: {domain_id} has no source patterns")
            continue
        if not any(any(path.is_file() for path in app_root.glob(str(pattern))) for pattern in source_patterns):
            errors.append(f"{domains_path}: {domain_id} source patterns match no files")
    return errors


def validate_sensitive_content(path: Path) -> list[str]:
    """Reject local developer paths and obvious credential material."""
    text = read_text(path)
    errors: list[str] = []
    if LOCAL_PATH_RE.search(text):
        errors.append(f"{path}: contains an absolute developer home path")
    if PRIVATE_KEY_RE.search(text):
        errors.append(f"{path}: contains private-key material")
    if API_SECRET_RE.search(text):
        errors.append(f"{path}: contains a value shaped like an API credential")
    return errors


def validate_generated_pages(generated_root: Path) -> list[str]:
    """Validate generated-page provenance and coverage status."""
    errors: list[str] = []
    generated_pages = sorted(generated_root.glob("*.md"))
    if not generated_pages:
        return [f"{generated_root}: no generated reference pages found"]
    for path in generated_pages:
        text = read_text(path)
        if not text.startswith(GENERATED_NOTICE):
            errors.append(f"{path}: generated notice missing")
    coverage_path = generated_root / "coverage.md"
    if coverage_path.is_file() and "**gap**" in read_text(coverage_path):
        errors.append(f"{coverage_path}: one or more curated domains report a documentation gap")
    return errors


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--app-root",
        type=Path,
        help="Override the auto-detected Gnosi application root.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Run every documentation validation and report all failures."""
    args = parse_args(argv or sys.argv[1:])
    app_root = (args.app_root or find_app_root(Path(__file__))).resolve()
    docs_root = app_root / "docs" / "engineering"
    generated_root = docs_root / "generated"
    domains_path = app_root / "pipeline" / "skills" / "technical_documentation" / "domains.json"
    mkdocs_path = app_root / "mkdocs.yml"
    errors: list[str] = []

    reviewed_pages = sorted(
        path for path in docs_root.rglob("*.md") if generated_root not in path.parents
    )
    if not reviewed_pages:
        errors.append(f"{docs_root}: no reviewed documentation pages found")
    for path in reviewed_pages:
        errors.extend(validate_metadata(path, app_root))
        errors.extend(validate_internal_links(path, docs_root))
        errors.extend(validate_sensitive_content(path))
    for path in sorted(generated_root.glob("*.md")):
        errors.extend(validate_internal_links(path, docs_root))
        errors.extend(validate_sensitive_content(path))
    errors.extend(validate_generated_pages(generated_root))
    errors.extend(validate_navigation(mkdocs_path, docs_root))
    errors.extend(validate_domains(domains_path, app_root))

    if errors:
        for error in errors:
            log.error(error)
        log.error("Documentation validation failed with %d error(s)", len(errors))
        return 1
    log.info(
        "Validated %d reviewed pages and %d generated pages",
        len(reviewed_pages),
        len(list(generated_root.glob("*.md"))),
    )
    return 0


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    raise SystemExit(main())
